{
  "hash": "8b4161cffcec8a94196205256b8feab9",
  "result": {
    "engine": "jupyter",
    "markdown": "# DS-MLOps Python Foundations\n## Part 1: Language Core\n\n**Python 3.12+ | Author: Anthony Faustine**\n\nPart 1 covers the Python language: types, strings, collections, operators, control flow, and comprehensions.\nAll examples come from a single realistic scenario: a **university analytics platform** that tracks student performance, course enrollment, and model experiment logs.\n\nPart 2 (`02-python-patterns.ipynb`) covers professional patterns: functions, modules, file I/O, dataclasses, and exception handling.\n\n\n### Callout guide\n\n<table style='border-collapse:collapse;width:60%'>\n<tr><td style='padding:6px 12px;background:#EAF3FA;border-left:4px solid #0369A1'><i class=\"bi bi-info-circle-fill\" style=\"color:#0369A1\"></i> <b>Key Concept</b></td><td style='padding:6px 12px'>Core idea with precise definition</td></tr>\n<tr><td style='padding:6px 12px;background:#EAF7F0;border-left:4px solid #059669'><i class=\"bi bi-journal-code\" style=\"color:#059669\"></i> <b>Example</b></td><td style='padding:6px 12px'>Worked illustration</td></tr>\n<tr><td style='padding:6px 12px;background:#FFF1E6;border-left:4px solid #EA580C'><i class=\"bi bi-puzzle-fill\" style=\"color:#EA580C\"></i> <b>Activity</b></td><td style='padding:6px 12px'>Hands-on challenge to try yourself</td></tr>\n<tr><td style='padding:6px 12px;background:#FEF2F2;border-left:4px solid #DC2626'><i class=\"bi bi-bug-fill\" style=\"color:#DC2626\"></i> <b>Common Mistake</b></td><td style='padding:6px 12px'>Bug pattern to watch for</td></tr>\n<tr><td style='padding:6px 12px;background:#F4F5F6;border-left:4px solid #6B7280'><i class=\"bi bi-lightbulb-fill\" style=\"color:#6B7280\"></i> <b>Pro Tip</b></td><td style='padding:6px 12px'>Production-grade habit</td></tr>\n</table>\n\n## Before You Begin\n\n### What is Python?\n\n**Python** is a general-purpose programming language created in 1991.\nA programming language is a set of rules for writing instructions a computer can execute.\nUnlike a spreadsheet, code lets you automate tasks, process millions of data points,\nand build models that learn from data.\n\n### Why Python for data science and AI?\n\nPython was not built for data science. It became the de facto standard because of\nthree compounding advantages:\n\n**1. Readable syntax.**\nPython code reads closer to plain English than any other mainstream language.\nA data scientist can focus on the algorithm, not the language syntax.\n`for score in scores: total += score` needs no translation.\n\n**2. A world-class numerical ecosystem.**\nThe entire scientific Python stack is Python-first:\n\n| Library | What it does |\n|---|---|\n| **NumPy** | Fast multi-dimensional arrays; the foundation everything else builds on |\n| **pandas** | Tabular data: load, clean, reshape, merge DataFrames |\n| **matplotlib / seaborn** | Visualisation: line charts, heatmaps, histograms |\n| **scikit-learn** | Classical ML: linear models, trees, SVMs, pipelines |\n| **PyTorch / JAX** | Deep learning: neural networks trained on GPU |\n| **HuggingFace Transformers** | Large language models and vision models |\n\nEvery major AI breakthrough in the last decade (ResNet, BERT, GPT, Llama) was released as Python code. Reproducing or building on that research requires Python.\n\n**3. Interactive computing with Jupyter.**\nJupyter notebooks let you run one cell at a time, see results immediately, and\niterate without a compile step. This matches how data exploration actually works:\ninspect the data, transform it, visualise, repeat.\n\n### What is a Jupyter notebook?\n\nThis file is a **Jupyter notebook**: a document that mixes formatted text\n(like this paragraph) with executable code. It consists of **cells**:\n\n- **Markdown cells** (like this one): formatted text, explanations, tables, equations.\n- **Code cells** (the grey boxes below): Python code. Press **Shift + Enter** to run\n  a cell; its output appears directly below.\n\n**Always run cells from top to bottom.** Later cells often use variables created\nin earlier ones. If something breaks, use **Kernel → Restart & Run All** to start fresh.\n\n### What we will build together\n\nEvery example uses the same scenario: a **university analytics platform** tracking\nstudent scores, course enrollments, and ML experiment logs.\nThe same data structures recur across every section so you can focus on the\nPython concept, not a new domain each time.\n\nBy the end of Part 1 you will be ready to work with real datasets using NumPy and pandas.\n\n### Python vs other languages\n\nThe best way to appreciate Python's readability is side-by-side comparison.\nHere is \"print Hello\" in three languages:\n\n**Java**: 5 lines of ceremony for one instruction:\n```java\npublic class Hello {\n    public static void main(String[] args) {\n        System.out.println(\"Hello\");\n    }\n}\n```\n\n**C++**: requires a header and an entry-point function:\n```cpp\n#include <iostream>\nint main() { std::cout << \"Hello\\n\"; }\n```\n\n**Python**: one line that reads like English:\n```python\nprint(\"Hello\")\n```\n\nThis gap widens as programs grow. A 300-line data pipeline in Python stays\nreadable; the equivalent in Java or C++ becomes much harder to navigate.\nThat is why Python dominates explorative, iterative work like data science and ML.\n\n## Learning Objectives\n\nBy the end of Part 1 you will be able to:\n\n| # | Skill | Covered in |\n|---|---|---|\n| 1 | Annotate variables with type hints (`list[float]`, `X | None`) | Sec. 1 |\n| 2 | Apply PEP 8 naming conventions (`snake_case`, `PascalCase`, `UPPER_SNAKE`) | Sec. 1.4 |\n| 3 | Clean, parse, and format strings | Sec. 2 |\n| 4 | Choose the right collection for any task | Sec. 3-7 |\n| 5 | Use `dict |` merge, `TypedDict`, and `NamedTuple` | Sec. 5, 4 |\n| 6 | Write `for`, `while`, `if/elif/else`, and `match/case` | Sec. 9-11 |\n| 7 | Replace loops with comprehensions and generators | Sec. 12 |\n| 8 | Apply the walrus operator `:=` where it clarifies code | Sec. 8 |\n\n> **Note on forward references:** Sections 2-7 occasionally use `for` loops and `class`\n> definitions before their dedicated sections (Sec. 10 and Part 2 respectively).\n> Whenever you see `for item in collection:` early, read it as \"repeat this block once\n> per item.\" Full explanations follow in the dedicated sections.\n\n## 1. Variables, Types & Type Hints\n\n### What is a variable?\n\nA **variable** is a named container that stores a value in your program's memory.\nThink of it as a labelled box:\n\n```\nname     ──►  \"Alice Kamau\"\ngpa      ──►  3.85\nenrolled ──►  True\n```\n\nYou create a variable with the **assignment operator** `=`:\n\n```python\nname = \"Alice Kamau\"   # create a box called 'name', put the value in it\n```\n\n> ⚠️ The `=` sign in Python means **assign** (store this value). It is NOT the\n> mathematical equals sign. To check equality, use `==` (two equals signs).\n\n### Python's four core types\n\nEvery value has a **type**: a label describing what kind of data it is:\n\n| Type | What it stores | Examples | Real-world use |\n|---|---|---|---|\n| `int` | Whole numbers | `42`, `2024001`, `-7` | Student IDs, epoch counts, ranks |\n| `float` | Decimal numbers | `3.85`, `0.001`, `92.3` | GPA, learning rate, accuracy |\n| `str` | Text (any characters) | `'Alice'`, `\"CS301\"` | Names, labels, file paths |\n| `bool` | True or False only | `True`, `False` | \"Is enrolled?\", \"Did it converge?\" |\n\nPython figures out the type of every value automatically. You never need to declare it.\n\n### Why add type hints?\n\nWithout hints, Python happily lets you store the wrong type in a variable:\n\n```python\ngpa = 3.85       # float ✓\ngpa = \"unknown\"  # str  - legal but wrong! breaks any later calculation\n```\n\n**Type hints** are optional annotations that make your intent explicit so that tools\ncan catch mistakes like the one above:\n\n```python\ngpa: float = 3.85   # hint says this must be a float\n```\n\nThe syntax is `name: type = value`. Hints are **not enforced at runtime**: Python\nwill not crash if you violate them, but the type checker `ty` will report an error\nthe moment you try to assign the wrong type.\n\n**Python 3.9+:** `list[int]`, `dict[str, float]` (no imports needed)\n**Python 3.10+:** `float | None` means \"a float, or nothing\" (replaces `Optional[float]`)\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Type Hints</span><br><br>\nA type hint annotates what type a variable <em>should</em> hold: <code>name: str = 'Alice'</code>.\nHints are read by the type checker (<code>ty</code>) and your editor, not enforced at runtime.\nAnnotate every variable, function parameter, and return value you write.\n</div>\n\nStart with the simplest possible case: create a few variables and print them.\nNo type hints yet, just the core idea of \"give a name to a value\":\n\n::: {#5 .cell execution_count=1}\n``` {.python .cell-code}\n# Your first Python variables: no type hints yet\n# The = sign puts the value on the right into the name on the left\nname = \"Alice Kamau\"  # text value (str)\nscore = 87.5  # decimal number (float)\nrank = 1  # whole number (int)\nenrolled = True  # True or False (bool)\n\n# print() displays a value in the output area below this cell\nprint(name)\nprint(score)\nprint(rank)\nprint(enrolled)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAlice Kamau\n87.5\n1\nTrue\n```\n:::\n:::\n\n\nPython knows the type of every value. `type()` reveals it, and `isinstance()` tests\nwhether a value belongs to a given type. Run this cell to confirm:\n\n::: {#7 .cell execution_count=2}\n``` {.python .cell-code}\n# type() tells you what Python has inferred\nprint(type(name))  # <class 'str'>\nprint(type(score))  # <class 'float'>\nprint(type(rank))  # <class 'int'>\nprint(type(enrolled))  # <class 'bool'>\n\n# Without hints, Python lets you overwrite with the wrong type: silently\nrank = \"first\"  # rank was an int, now it's a str: Python allows it\nprint(f\"rank is now a {type(rank).__name__}\")  # str!\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'str'>\n<class 'float'>\n<class 'int'>\n<class 'bool'>\nrank is now a str\n```\n:::\n:::\n\n\nThat last reassignment (`rank = 'first'`) would silently break any code that later\ntries to do arithmetic with `rank`. Type hints prevent this by making your intent\nexplicit. Now see the same variables with proper annotations:\n\n::: {#9 .cell execution_count=3}\n``` {.python .cell-code}\n# --- Student enrollment record ---\nstudent_id: int = 2024001\nfull_name: str = \"Maria Garcia\"\ngpa: float = 3.85\nis_enrolled: bool = True\nscholarship_amount: float | None = None  # union type: float or None (Python 3.10+)\n\nprint(f\"Student : {full_name} (ID: {student_id})\")\nprint(f\"GPA     : {gpa}  Enrolled: {is_enrolled}\")\nprint(f\"Scholar.: {scholarship_amount}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStudent : Maria Garcia (ID: 2024001)\nGPA     : 3.85  Enrolled: True\nScholar.: None\n```\n:::\n:::\n\n\nRun this to see Python's runtime type information. `isinstance()` is preferred over `type()`\nbecause it handles class hierarchies. `bool` is a subclass of `int`, so\n`isinstance(True, int)` returns `True`:\n\n::: {#11 .cell execution_count=4}\n``` {.python .cell-code}\n# isinstance() is preferred over type() for checks: handles subclasses\nprint(f\"type(gpa)                      -> {type(gpa)}\")\nprint(f\"isinstance(gpa, float)         -> {isinstance(gpa, float)}\")\nprint(f\"isinstance(gpa, int | float)  -> {isinstance(gpa, int | float)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntype(gpa)                      -> <class 'float'>\nisinstance(gpa, float)         -> True\nisinstance(gpa, int | float)  -> True\n```\n:::\n:::\n\n\nPython also has a built-in **complex number** type, used in signal processing and Fourier analysis:\n\n::: {#13 .cell execution_count=5}\n``` {.python .cell-code}\n# complex numbers: real + imaginary parts\nfrequency: complex = 3 + 2j  # j is the imaginary unit\nprint(f\"complex   : {frequency}\")\nprint(f\"real part : {frequency.real}\")\nprint(f\"imag part : {frequency.imag}\")\nprint(f\"magnitude : {abs(frequency):.3f}\")  # |z| = sqrt(real² + imag²)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncomplex   : (3+2j)\nreal part : 3.0\nimag part : 2.0\nmagnitude : 3.606\n```\n:::\n:::\n\n\n<div style='background:#F4F5F6;border-left:5px solid #6B7280;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#6B7280;font-weight:bold'><i class=\"bi bi-lightbulb-fill\"></i> Pro Tip: f-string debugging with <code>=</code></span><br><br>\nPython 3.8+ added <code>f'{var=}'</code> which prints the variable name <b>and</b> its value in one shot.\nThis is faster than writing <code>print(f'var = {var}')</code> and far more useful during exploration.\n</div>\n\n::: {#15 .cell execution_count=6}\n``` {.python .cell-code}\n# f'{var=}': name + value, invaluable for debugging\nloss: float = 0.4231\nepoch: int = 12\nlearning_rate: float = 0.001\n\nprint(f\"{loss=}\")  # loss=0.4231\nprint(f\"{epoch=}\")  # epoch=12\nprint(f\"{learning_rate=}\")  # learning_rate=0.001\nprint(f\"{loss:.4f}\")  # 0.4231  (formatted, no name)\nprint(f\"{loss * 0.9 = }\")  # loss * 0.9 = 0.38078999999999997 (expressions too)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nloss=0.4231\nepoch=12\nlearning_rate=0.001\n0.4231\nloss * 0.9 = 0.38078999999999996\n```\n:::\n:::\n\n\n<div style='background:#FFF1E6;border-left:5px solid #EA580C;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#9A3412;font-weight:bold'><i class=\"bi bi-puzzle-fill\"></i> Activity 1 - Annotate a Dataset Row</span><br><br>\n<b>Goal:</b> Replace each <code>...</code> with the correct type from the table above\n(<code>int</code>, <code>float</code>, <code>str</code>, <code>bool</code>, or <code>float | None</code>).<br><br>\n<b>How to decide:</b> look at the value on the right of <code>=</code> and ask:\n\"Is it a whole number? A decimal? Text? True/False? Could it be missing?\"<br><br>\n<b>Expected:</b> after filling in the hints, your editor should show no type errors.\n</div>\n\n::: {#17 .cell execution_count=7}\n``` {.python .cell-code}\n# TODO: replace each ... with the correct type annotation\ncourse_code: ... = \"CS301\"\ncredits: ... = 3\npass_rate: ... = 0.87\ninstructor: ... = \"Dr. Nkosi\"\nlab_room: ... = None  # lab not yet assigned\nis_core_course: ... = True\n\n# When you are done, print each variable with f'{var=}'\nprint(f\"{course_code=}\")\nprint(f\"{credits=}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncourse_code='CS301'\ncredits=3\n```\n:::\n:::\n\n\n### 1.4 Naming Conventions ([PEP 8](https://peps.python.org/pep-0008/))\n\n[PEP 8](https://peps.python.org/pep-0008/) (Python Enhancement Proposal 8) is the\n**official Python style guide**, written by Python's creator Guido van Rossum.\nEvery serious Python project follows it; the linter `ruff` enforces it automatically\n(`ruff check .`).\n\nPython defines four naming styles. Each signals a specific **role** in the language:\n\n\n#### `snake_case`\nAll lowercase, words joined by underscores.\nThe default style for **everything that is not a class or a constant**:\nvariables, functions, method names, and module file names.\n\n```python\nstudent_gpa    = 3.85     # variable\nlearning_rate  = 0.001    # variable\ndef load_data(): ...      # function name\n# module file: data_loader.py\n```\n\n\n#### `PascalCase` (also called UpperCamelCase)\nEvery word starts with a capital letter; no underscores.\nReserved exclusively for **class names**, `NamedTuple`s, and `TypedDict`s --\nanything that defines a new **type**.\n\n```python\nclass StudentRecord: ...      # class\nclass ModelConfig: ...        # class\nclass ExperimentRow(TypedDict): ...   # TypedDict\n```\n\n\n#### `UPPER_SNAKE_CASE`\nAll uppercase, words separated by underscores.\nUse only for **module-level constants**: values set once, never reassigned.\nThe style signals to every reader: \"do not change this.\"\n\n```python\nMAX_EPOCHS       = 100\nBASE_LEARNING_RATE = 0.001\nDATASET_PATH     = 'data/students.csv'\n```\n\n\n#### `_leading_underscore`\nA single underscore prefix signals that a name is **private / internal** --\nan implementation detail not meant to be called from outside the module or class.\nPython does not enforce this; it is a convention your team respects.\n\n```python\ndef _validate_scores(scores): ...  # internal helper\n_cache: dict[str, float] = {}      # internal state\n```\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: PEP 8 naming</span><br><br>\n<code>snake_case</code> for variables &amp; functions &nbsp;|&nbsp;\n<code>PascalCase</code> for classes &amp; types &nbsp;|&nbsp;\n<code>UPPER_SNAKE</code> for constants &nbsp;|&nbsp;\n<code>_leading</code> for internals.<br>\nThe computer ignores these conventions. Your teammates will not.\nRun <code>ruff check .</code> to catch violations automatically.\n</div>\n\n<div style='background:#FEF2F2;border-left:5px solid #DC2626;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#991B1B;font-weight:bold'><i class=\"bi bi-bug-fill\"></i> Common Mistake: Mixing styles</span><br><br>\n<code>StudentGPA = 3.85</code> looks like a class (PascalCase), not a variable.<br>\n<code>LOAD_DATA = lambda: ...</code> looks like a constant, not a function.<br>\nMisleading names cause bugs that are hard to find. Be consistent.\n</div>\n\n::: {#19 .cell execution_count=8}\n``` {.python .cell-code}\n# snake_case: variables and functions\nmax_epochs: int = 100\nlearning_rate: float = 0.001\nmodel_accuracy: float = 0.945\nis_converged: bool = False  # bool names read like a yes/no question\nstudent_gpa_scores: list[float] = [3.95, 3.45, 3.88]\n\n# UPPER_SNAKE_CASE: module-level constants\nMAX_BATCH_SIZE: int = 32\nDATASET_PATH: str = \"data/students.csv\"\n\n# Avoid: cryptic abbreviations\n# lr   = 0.001    # unclear: is this learning rate? loss ratio?\n# ma   = 0.945    # unclear\n# b    = 32       # unclear\n\n# ruff catches naming violations:\n#   ruff check tutorials/  -->  E741 Ambiguous variable name: 'l'\n\nprint(f\"Accuracy: {model_accuracy:.1%}\")  # .1% formats as a percentage\nprint(f\"Converged: {is_converged}\")\nprint(f\"Dataset: {DATASET_PATH}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAccuracy: 94.5%\nConverged: False\nDataset: data/students.csv\n```\n:::\n:::\n\n\n## 2. Strings & String Methods\n\nA **string** is any piece of text: a student name, a course code, a log message,\na file path. Create one by wrapping text in matching quotes:\n\n```python\nname   = 'Alice Kamau'       # single quotes\ncourse = \"Machine Learning\"  # double quotes - both work identically\n```\n\nStrings are used constantly in data science: reading CSV column headers, cleaning\nfield values, building file paths, and formatting model output.\nPython provides dozens of built-in methods, no imports needed.\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Strings are Immutable Sequences</span><br><br>\nA <code>str</code> is an ordered, <b>immutable</b> sequence of Unicode characters.\nEvery string method returns a <b>new</b> string. The original is never changed.\nIn data science you use strings to parse CSV rows, clean field values, build file paths, and format model output.\nMastering the handful of methods below covers 95% of string work you will encounter.\n</div>\n\n::: {#21 .cell execution_count=9}\n``` {.python .cell-code}\n# f-strings: the standard for formatting output in Python 3.6+\nname: str = \"Alice Kamau\"\nscore: float = 87.5\nrank: int = 3\n\nprint(f\"Student : {name}\")\nprint(f\"Score   : {score:.1f}%\")  # one decimal place\nprint(f\"Score   : {score:.0f}%\")  # rounded to integer\nprint(f\"Rank    : #{rank:02d}\")  # zero-padded two digits\nprint(f\"Pass?   : {'Yes' if score >= 70 else 'No'}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStudent : Alice Kamau\nScore   : 87.5%\nScore   : 88%\nRank    : #03\nPass?   : Yes\n```\n:::\n:::\n\n\nAlignment specifiers (`{name:<8}`, `{score:5.1f}`) format values into fixed-width columns.\nThis cell uses a `for` loop for display. It is introduced properly in Sec. 11.\nRead `for name, s in [...]:` as \"for each (name, score) pair in the list, do this\":\n\n::: {#23 .cell execution_count=10}\n``` {.python .cell-code}\n# Alignment: useful for building readable reports\nfor student, s in [(\"Alice\", 92.1), (\"Bob\", 74.8), (\"Carol\", 88.5)]:\n    bar = \"#\" * int(s // 10)\n    print(f\"{student:<8} {s:5.1f}  {bar}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAlice     92.1  #########\nBob       74.8  #######\nCarol     88.5  ########\n```\n:::\n:::\n\n\n<div style='background:#F4F5F6;border-left:5px solid #6B7280;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#6B7280;font-weight:bold'><i class=\"bi bi-lightbulb-fill\"></i> Pro Tip: Recognising Older Formatting Styles</span><br><br>\nYou will encounter two older styles in legacy code and tutorials. Know them so you can read them, but write f-strings.<br><br>\n<code>print(\"Accuracy: %d%%\" % 92)</code> &nbsp;&nbsp; ← <b>%-formatting</b> (Python 2 era, still valid)<br>\n<code>print(\"Accuracy: {}\".format(92))</code> &nbsp;&nbsp; ← <b>.format()</b> (Python 3.0+, more flexible than %)<br>\n<code>print(f\"Accuracy: {acc}\")</code> &nbsp;&nbsp; ← <b>f-strings</b> (Python 3.6+, fastest and most readable, use this)\n</div>\n\n### Cleaning & Parsing\nReal-world data always arrives dirty: extra spaces, inconsistent delimiters, mixed case.\n`strip()` + `split()` is the most common two-step clean-up in any data pipeline:\n\n::: {#26 .cell execution_count=11}\n``` {.python .cell-code}\n# Cleaning and parsing: the most common string operations in data work\nraw_row: str = \"  Alice Kamau , 2024001 , 3.95 , Computer Science  \"\n\n# strip() removes leading and trailing whitespace\ncleaned: str = raw_row.strip()\n\n# split() on a delimiter returns a list; strip each part too\nparts: list[str] = [p.strip() for p in cleaned.split(\",\")]\nname, sid, gpa_str, major = parts\n\nprint(f\"Name  : {name!r}\")\nprint(f\"ID    : {sid}\")\nprint(f\"GPA   : {float(gpa_str):.2f}\")\nprint(f\"Major : {major}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nName  : 'Alice Kamau'\nID    : 2024001\nGPA   : 3.95\nMajor : Computer Science\n```\n:::\n:::\n\n\n`join()` is the inverse of `split()`. It reassembles a list of strings into one string\nwith a chosen separator. `replace()` and case methods normalise individual field values:\n\n::: {#28 .cell execution_count=12}\n``` {.python .cell-code}\n# join() is the inverse of split(): reassemble with a new delimiter\ntsv_row: str = \"\\t\".join(parts)\nprint(f\"TSV   : {tsv_row!r}\")\n\n# replace(): swap delimiters or fix typos\nprint(cleaned.replace(\",\", \" |\"))\n\n# Case methods\ntag: str = \"  machine_learning  \"\nprint(tag.strip().replace(\"_\", \" \").title())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTSV   : 'Alice Kamau\\t2024001\\t3.95\\tComputer Science'\nAlice Kamau  | 2024001  | 3.95  | Computer Science\nMachine Learning\n```\n:::\n:::\n\n\n### Searching & Slicing\nTest membership, find positions, and count occurrences, all without writing a loop:\n\n::: {#30 .cell execution_count=13}\n``` {.python .cell-code}\n# Searching strings: common in log parsing and feature extraction\nlog: str = \"[ERROR] epoch 42: validation loss exceeded threshold (loss=1.234)\"\n\nprint(f\"starts with [ERROR]  : {log.startswith('[ERROR]')}\")\nprint(f\"ends with threshold  : {log.endswith('threshold')}\")\nprint(f'contains \"loss\"      : {\"loss\" in log}')\nprint(f'find \"epoch\"         : index {log.find(\"epoch\")}')\nprint(f'count of \"e\"         : {log.count(\"e\")}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstarts with [ERROR]  : True\nends with threshold  : False\ncontains \"loss\"      : True\nfind \"epoch\"         : index 8\ncount of \"e\"         : 6\n```\n:::\n:::\n\n\nString slicing (`s[start:stop]`) extracts a substring by position, using the same syntax\nas list slicing. `rpartition(sep)` splits at the **last** occurrence of `sep`, returning\n`(before, sep, after)`, the cleanest way to separate a filename from its extension:\n\n::: {#32 .cell execution_count=14}\n``` {.python .cell-code}\nlog: str = \"[ERROR] epoch 42: validation loss exceeded threshold (loss=1.234)\"\n\n# Extract structured data from a log line\nepoch_part: str = log.split(\"epoch \")[1].split(\":\")[0]\nprint(f\"Epoch number : {epoch_part}\")\n\n# Slicing: same rules as lists\nprefix: str = log[:7]  # '[ERROR]'\nbody: str = log[9:]\nprint(f\"Prefix : {prefix!r}\")\nprint(f\"Body   : {body!r}\")\n\n# rpartition(): split at the LAST occurrence of a separator\nfilename: str = \"model_experiment_run_42.parquet\"\nstem, _, ext = filename.rpartition(\".\")\nprint(f\"stem={stem!r}  ext={ext!r}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEpoch number : 42\nPrefix : '[ERROR]'\nBody   : 'poch 42: validation loss exceeded threshold (loss=1.234)'\nstem='model_experiment_run_42'  ext='parquet'\n```\n:::\n:::\n\n\n<div style='background:#FFF1E6;border-left:5px solid #EA580C;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#9A3412;font-weight:bold'><i class=\"bi bi-puzzle-fill\"></i> Activity 2 - Parse a Messy Log Line</span><br><br>\n<b>Goal:</b> Extract the model name, epoch, and loss value from the raw log string below into typed variables.<br><br>\n<pre style='background:#FCE8DA;padding:10px;border-radius:4px;font-size:0.9em'>raw = '  [INFO]  model=RandomForest | epoch=  5 | train_loss=0.3421 | val_loss=0.3812  '\n\n# Expected\nmodel_name  = 'RandomForest'\nepoch       = 5\ntrain_loss  = 0.3421\nval_loss    = 0.3812</pre>\n<b>Hint:</b> Use <code>strip()</code>, <code>split('|')</code>, and <code>split('=')</code>.\n</div>\n\n::: {#34 .cell execution_count=15}\n``` {.python .cell-code}\nraw: str = \"  [INFO]  model=RandomForest | epoch=  5 | train_loss=0.3421 | val_loss=0.3812  \"\n\n# TODO: parse raw into the variables below\nmodel_name: str = ...\nepoch: int = ...\ntrain_loss: float = ...\nval_loss: float = ...\n\n# Verify\nprint(f\"{model_name=}  {epoch=}  {train_loss=}  {val_loss=}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmodel_name=Ellipsis  epoch=Ellipsis  train_loss=Ellipsis  val_loss=Ellipsis\n```\n:::\n:::\n\n\n## 3. Collections: List\n\nA **list** is Python's most versatile built-in container:\nan **ordered, mutable** sequence of items of any type.\n\n```python\nscores  : list[float] = [78.0, 85.5, 92.0]   # floats\nnames   : list[str]   = ['Alice', 'Bob']       # strings\nmixed   :  list       = [42, 'label', True]    # any types (avoid in practice)\n```\n\n**When to use a list:**\n- Order matters: items have a defined first and last position\n- You need to add, remove, or change elements after creation\n- You are collecting results in a loop: training losses, processed records, file paths\n\n**Key operations at a glance:**\n\n| Operation | Syntax | Notes |\n|---|---|---|\n| Index | `a[i]` | 0-based; negative counts from end |\n| Slice | `a[start:stop:step]` | Returns new list; stop is exclusive |\n| Append | `a.append(x)` | Add one item to the end |\n| Extend | `a.extend(iterable)` | Add all items from another sequence |\n| Insert | `a.insert(i, x)` | Insert before index `i` |\n| Remove | `a.remove(x)` | Remove first occurrence of value `x` |\n| Pop | `a.pop(i)` | Remove & return item at index `i` (default: last) |\n| Delete | `del a[i]` / `del a[i:j]` | Remove item or slice, returns nothing |\n| Clear | `a.clear()` | Remove all items (same as `del a[:]`) |\n| Membership | `x in a` | Returns `True` / `False` |\n| Length | `len(a)` | Number of items |\n| Sort | `a.sort()` / `sorted(a)` | In-place vs new list |\n| Count | `a.count(x)` | Occurrences of `x` |\n| Index | `a.index(x)` | Position of first `x` |\n| Copy | `a.copy()` | Shallow independent copy |\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Ordered &amp; Mutable</span><br><br>\nA list maintains <b>insertion order</b> and supports <b>in-place modification</b>.\nAnnotate as <code>list[int]</code> (Python 3.9+, no import needed).<br>\nFull reference: <a href=\"https://docs.python.org/3/tutorial/datastructures.html\" style=\"color:#0369A1\">docs.python.org: 5.1 More on Lists</a>\n</div>\n\n<div style='background:#FEF2F2;border-left:5px solid #DC2626;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#991B1B;font-weight:bold'><i class=\"bi bi-bug-fill\"></i> Common Mistake: Assignment Is Not a Copy</span><br><br>\n<code>b = a</code> makes <code>b</code> point to the <b>same</b> list.\nMutating <code>b</code> also changes <code>a</code>.<br>\nUse <code>b = a.copy()</code> or <code>b = a[:]</code> for an independent copy.\n</div>\n\n::: {#36 .cell execution_count=16}\n``` {.python .cell-code}\n# Quiz scores for a cohort of students\nquiz_scores: list[float] = [78.0, 85.5, 92.0, 88.5, 95.0, 67.0, 81.0]\n\n# Indexing: 0-based; negative index counts from the end\nprint(f\"First  : {quiz_scores[0]}\")\nprint(f\"Last   : {quiz_scores[-1]}\")\nprint(f\"[1:4]  : {quiz_scores[1:4]}\")\nprint(f\"[::2]  : {quiz_scores[::2]}\")  # every other element\n\n# Aggregates\nn: int = len(quiz_scores)\nmean: float = sum(quiz_scores) / n\nprint(f\"n={n}  min={min(quiz_scores)}  max={max(quiz_scores)}  mean={mean:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFirst  : 78.0\nLast   : 81.0\n[1:4]  : [85.5, 92.0, 88.5]\n[::2]  : [78.0, 92.0, 95.0, 81.0]\nn=7  min=67.0  max=95.0  mean=83.9\n```\n:::\n:::\n\n\n### Slicing\n\nA **slice** extracts a sub-list without modifying the original.\nThe syntax is `a[start : stop : step]`:\n\n| Part | Default | Meaning |\n|---|---|---|\n| `start` | `0` | Index to begin from (inclusive) |\n| `stop` | `len(a)` | Index to stop at (**exclusive**: this element is NOT included) |\n| `step` | `1` | How many positions to advance each time |\n\n```python\na = [10, 20, 30, 40, 50]\na[1:4]    # [20, 30, 40]   - stop=4 is excluded\na[:3]     # [10, 20, 30]   - start defaults to 0\na[2:]     # [30, 40, 50]   - stop defaults to end\na[::2]    # [10, 30, 50]   - every second element\na[::-1]   # [50, 40, 30, 20, 10] - reversed\na[:]      # [10, 20, 30, 40, 50] - full copy (shallow)\n```\n\nSlicing never raises an `IndexError`. Out-of-range start/stop are clamped silently.\n\n::: {#38 .cell execution_count=17}\n``` {.python .cell-code}\nquiz_scores: list[float] = [78.0, 85.5, 92.0, 88.5, 95.0, 67.0, 81.0]\n\n# Basic slices\nprint(f\"First 3     : {quiz_scores[:3]}\")  # [78.0, 85.5, 92.0]\nprint(f\"Last 3      : {quiz_scores[-3:]}\")  # [95.0, 67.0, 81.0]\nprint(f\"Middle      : {quiz_scores[2:5]}\")  # [92.0, 88.5, 95.0]\n\n# Step\nprint(f\"Every 2nd   : {quiz_scores[::2]}\")  # [78.0, 92.0, 95.0, 81.0]\nprint(f\"Reversed    : {quiz_scores[::-1]}\")\n\n# Shallow copy via slice\ncopy_via_slice: list[float] = quiz_scores[:]\ncopy_via_slice[0] = 0.0\nprint(f\"Original[0] : {quiz_scores[0]}\")  # unchanged: 78.0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFirst 3     : [78.0, 85.5, 92.0]\nLast 3      : [95.0, 67.0, 81.0]\nMiddle      : [92.0, 88.5, 95.0]\nEvery 2nd   : [78.0, 92.0, 95.0, 81.0]\nReversed    : [81.0, 67.0, 95.0, 88.5, 92.0, 85.5, 78.0]\nOriginal[0] : 78.0\n```\n:::\n:::\n\n\n`=` copies the **reference**, not the data. Both names then point to the same list in\nmemory. Confirm the difference between a reference and an independent copy:\n\n::: {#40 .cell execution_count=18}\n``` {.python .cell-code}\n# Copy vs reference: a critical distinction\nquiz_scores: list[float] = [78.0, 85.5, 92.0, 88.5, 95.0, 67.0, 81.0]\n\nbackup: list[float] = quiz_scores.copy()  # independent copy\nref: list[float] = quiz_scores  # same object!\nquiz_scores[0] = 99.0\n\nprint(\"After quiz_scores[0] = 99.0:\")\nprint(f\"  quiz_scores[0] : {quiz_scores[0]}\")\nprint(f\"  ref[0]         : {ref[0]}\")  # also changed: same object\nprint(f\"  backup[0]      : {backup[0]}\")  # unchanged: independent copy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAfter quiz_scores[0] = 99.0:\n  quiz_scores[0] : 99.0\n  ref[0]         : 99.0\n  backup[0]      : 78.0\n```\n:::\n:::\n\n\n### Modifying Lists\n\n**Mutability** means a value can be changed after it is created.\nA list is **mutable**: you can add, remove, or replace any element at any time,\nwithout creating a new list. This is unlike strings and tuples, which are\n**immutable**: once created, their contents cannot change.\n\n| Type | Mutable? | What it means |\n|---|---|---|\n| `list` | Yes | Change any element, add or remove items freely: `scores[0] = 99` |\n| `str` | No | Methods like `.upper()` return a *new* string; the original is untouched |\n| `tuple` | No | Elements are fixed at creation and cannot be reassigned |\n\nBecause lists are mutable, the methods below **modify the original list in place**\nand return `None`, not a new list.\n\n::: {#42 .cell execution_count=19}\n``` {.python .cell-code}\nscores: list[float] = [85.0, 92.0, 78.0, 65.0, 88.0]\n\n#: Adding items --\nscores.append(95.0)  # add one item to the end       [85, 92, 78, 65, 88, 95]\nscores.insert(1, 90.0)  # insert 90.0 before index 1\nscores.extend([81.5, 76.0])  # add all items from another list\n\n#: Removing items --\nscores.remove(65.0)  # remove first occurrence of 65.0 (raises ValueError if absent)\nlast = scores.pop()  # remove and return last item\nsecond = scores.pop(1)  # remove and return item at index 1\ndel scores[0]  # remove item at index 0 (no return value)\n# del scores[1:3]             # delete a slice: removes multiple items at once\n\n#: Membership test --\nprint(f\"95.0 in scores   : {95.0 in scores}\")  # True / False\nprint(f\"999.0 in scores  : {999.0 in scores}\")\n\nprint(f\"scores : {scores}\")\nprint(f\"popped : last={last}, second={second}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n95.0 in scores   : True\n999.0 in scores  : False\nscores : [92.0, 78.0, 88.0, 95.0, 81.5]\npopped : last=76.0, second=90.0\n```\n:::\n:::\n\n\n### List as a Stack & clear()\n\nA **stack** is a Last-In, First-Out (LIFO) structure: the last item appended is the\nfirst one popped. Lists implement this naturally with `append()` + `pop()`.\n\n`clear()` removes all items from the list in place (equivalent to `del a[:]`).\n\n::: {#44 .cell execution_count=20}\n``` {.python .cell-code}\n# List as a LIFO stack: useful for depth-first search, undo history, backtracking\ncall_stack: list[str] = []\n\n# Push\ncall_stack.append(\"load_data\")\ncall_stack.append(\"clean_data\")\ncall_stack.append(\"train_model\")\nprint(f\"Stack (top is last) : {call_stack}\")\n\n# Pop (LIFO order)\nwhile call_stack:\n    task = call_stack.pop()\n    print(f\"  Processing: {task}\")\n\nprint(f\"Stack after popping : {call_stack}\")\n\n# clear(): empty a list in place (the name 'call_stack' still exists)\ncall_stack.extend([\"task_a\", \"task_b\", \"task_c\"])\ncall_stack.clear()\nprint(f\"After clear()       : {call_stack}\")  # []\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStack (top is last) : ['load_data', 'clean_data', 'train_model']\n  Processing: train_model\n  Processing: clean_data\n  Processing: load_data\nStack after popping : []\nAfter clear()       : []\n```\n:::\n:::\n\n\n`sorted()` returns a **new** sorted list; `.sort()` modifies the list **in place** and\nreturns `None`. Assigning the result of `.sort()` is a common silent bug:\n\n::: {#46 .cell execution_count=21}\n``` {.python .cell-code}\n# sorted() returns a new list; .sort() modifies in place\nascending: list[float] = sorted(scores)\ndescending: list[float] = sorted(scores, reverse=True)\nprint(f\"asc    : {ascending}\")\nprint(f\"desc   : {descending}\")\n\n# Search\nprint(f\"count of 85.0 : {scores.count(85.0)}\")\nprint(f\"index of 92.0 : {scores.index(92.0)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nasc    : [78.0, 81.5, 88.0, 92.0, 95.0]\ndesc   : [95.0, 92.0, 88.0, 81.5, 78.0]\ncount of 85.0 : 0\nindex of 92.0 : 0\n```\n:::\n:::\n\n\n<div style='background:#FFF1E6;border-left:5px solid #EA580C;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#9A3412;font-weight:bold'><i class=\"bi bi-puzzle-fill\"></i> Activity 3 - Summarise a Score List</span><br><br>\n<b>Goal:</b> Given the raw scores below, produce a cleaned, sorted list and a summary string.<br><br>\n<pre style='background:#FCE8DA;padding:10px;border-radius:4px;font-size:0.9em'>raw = [91.0, None, 74.5, 88.0, None, 63.0, 95.5, 80.0]\n\n# Expected output\nclean = [63.0, 74.5, 80.0, 88.0, 91.0, 95.5]   # sorted, None removed\nsummary = 'n=6  min=63.0  max=95.5  mean=82.0'</pre>\n<b>Hint:</b> Filter with a list comprehension, then use <code>sorted()</code>.\n</div>\n\n::: {#48 .cell execution_count=22}\n``` {.python .cell-code}\nraw: list[float | None] = [91.0, None, 74.5, 88.0, None, 63.0, 95.5, 80.0]\n\n# TODO: build clean (filtered + sorted) and print summary\nclean: list[float] = ...\nprint(f\"clean   : {clean}\")\nprint(f\"n={len(clean)}  min={min(clean)}  max={max(clean)}  mean={sum(clean) / len(clean):.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nclean   : Ellipsis\n```\n:::\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-red-fg\">---------------------------------------------------------------------------</span>\n<span class=\"ansi-red-fg\">TypeError</span>                                 Traceback (most recent call last)\n<span class=\"ansi-cyan-fg\">Cell</span><span class=\"ansi-cyan-fg\"> </span><span class=\"ansi-green-fg\">In[22]</span><span class=\"ansi-green-fg\">, line 6</span>\n<span class=\"ansi-green-fg\">      4</span> clean: <span style=\"color:rgb(0,135,0)\">list</span>[<span style=\"color:rgb(0,135,0)\">float</span>] = ...\n<span class=\"ansi-green-fg\">      5</span> <span style=\"color:rgb(0,135,0)\">print</span>(<span class=\"ansi-yellow-fg\">f</span><span class=\"ansi-yellow-fg\">\"</span><span class=\"ansi-yellow-fg\">clean   : </span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span>clean<span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\">\"</span>)\n<span class=\"ansi-green-fg\">----&gt; </span><span class=\"ansi-green-fg\">6</span> <span style=\"color:rgb(0,135,0)\">print</span>(<span class=\"ansi-yellow-fg\">f</span><span class=\"ansi-yellow-fg\">\"</span><span class=\"ansi-yellow-fg\">n=</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span><span style=\"color:rgb(0,135,0)\" class=\"ansi-yellow-bg\">len</span><span class=\"ansi-yellow-bg\">(</span><span class=\"ansi-yellow-bg\">clean</span><span class=\"ansi-yellow-bg\">)</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\">  min=</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span><span style=\"color:rgb(0,135,0)\">min</span>(clean)<span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\">  max=</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span><span style=\"color:rgb(0,135,0)\">max</span>(clean)<span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\">  mean=</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span><span style=\"color:rgb(0,135,0)\">sum</span>(clean)<span style=\"color:rgb(188,188,188)\"> </span>/<span style=\"color:rgb(188,188,188)\"> </span><span style=\"color:rgb(0,135,0)\">len</span>(clean)<span style=\"font-weight:bold;color:rgb(175,95,135)\">:</span><span class=\"ansi-yellow-fg\">.1f</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\">\"</span>)\n\n<span class=\"ansi-red-fg\">TypeError</span>: object of type 'ellipsis' has no len()</pre>\n```\n:::\n\n:::\n:::\n\n\n## 4. Collections: Tuple & NamedTuple\n\nA **tuple** is an **ordered, immutable** sequence, similar to a list, but its\ncontents are fixed at creation. You cannot add, remove, or change any element.\n\n**Immutable** means locked. Once you write `coords = (1.29, 36.82)`, those two\nnumbers cannot be replaced. This is intentional: immutability makes tuples safe\nto use as dictionary keys, pass between functions, and share across threads without\nrisk of accidental modification.\n\n**When to use a tuple:**\n- The number of elements is fixed by design (a coordinate pair is always 2 values)\n- Returning multiple values from a function (Python packs them into a tuple)\n- You need a hashable key for a `dict` or `set` (lists cannot be dict keys)\n- Signalling to a reader that this data must not change\n\n**Key operations at a glance:**\n\n| Operation | Syntax | Notes |\n|---|---|---|\n| Index | `t[i]` | Same as list; negative index counts from end |\n| Slice | `t[start:stop:step]` | Returns a new tuple |\n| Unpack | `a, b, c = t` | Assign each element to a name |\n| Extended unpack | `first, *rest = t` | `*rest` collects remaining into a list |\n| Swap | `a, b = b, a` | Pythonic; no temporary variable needed |\n| Length | `len(t)` | Number of elements |\n| Membership | `x in t` | `True` / `False` |\n| Count | `t.count(x)` | Number of occurrences of `x` |\n| Find | `t.index(x)` | Index of first occurrence of `x` |\n| Concatenate | `t1 + t2` | Returns a new, longer tuple |\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Ordered &amp; Immutable</span><br><br>\nUse a <code>tuple</code> for data that <b>must not change</b>: coordinate pairs, database rows,\nfunction return values. Annotate the type of each position: <code>tuple[str, int, float]</code>.<br><br>\n<code>typing.NamedTuple</code> adds field names and type hints, giving you a lightweight,\ntyped, self-documenting record with zero runtime overhead over a plain tuple.\n</div>\n\n> **Class syntax note:** `NamedTuple` uses the `class` keyword.\n> Full class mechanics are covered in Part 2. For now, read\n> `class Foo(NamedTuple):` as \"define a named-tuple type called Foo with these fields.\"\n\n::: {#50 .cell execution_count=23}\n``` {.python .cell-code}\n# Tuple: annotate with the exact types of each position\nrecord: tuple[str, int, float] = (\"Alice Kamau\", 2024001, 3.95)\n\n# Unpack all elements at once\nname, student_id, gpa = record\nprint(f\"{name=}  {student_id=}  {gpa=}\")\n\n# Extended unpacking with *\nfirst, *middle, last = (82.0, 91.5, 74.0, 88.0, 95.5)\nprint(f\"{first=}  {middle=}  {last=}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nname='Alice Kamau'  student_id=2024001  gpa=3.95\nfirst=82.0  middle=[91.5, 74.0, 88.0]  last=95.5\n```\n:::\n:::\n\n\nPython's swap idiom packs two values into a tuple and immediately unpacks them\nin the opposite order, no temporary variable needed. Tuples also enforce\nimmutability at runtime:\n\n::: {#52 .cell execution_count=24}\n``` {.python .cell-code}\n# Pythonic variable swap: no temp variable needed\nx, y = \"train\", \"val\"\nx, y = y, x\nprint(f\"After swap: {x=}  {y=}\")\n\n# Immutability: tuples cannot be changed after creation\nrecord: tuple[str, int, float] = (\"Alice Kamau\", 2024001, 3.95)\ntry:\n    record[0] = \"Bob\"  # type: ignore[index]\nexcept TypeError as exc:\n    print(f\"Immutable: {exc}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAfter swap: x='val'  y='train'\nImmutable: 'tuple' object does not support item assignment\n```\n:::\n:::\n\n\n### NamedTuple: Named, Typed Fields\n`NamedTuple` gives a plain tuple field names and type annotations.\nIt uses `class` syntax (see the note in the section header). For now, read this as\n\"create a named tuple type with these typed fields\":\n\n::: {#54 .cell execution_count=25}\n``` {.python .cell-code}\nfrom typing import NamedTuple\n\n\nclass StudentRecord(NamedTuple):\n    \"\"\"Typed, immutable student record.\"\"\"\n\n    name: str\n    student_id: int\n    gpa: float\n    major: str = \"Undeclared\"  # field with default value\n```\n:::\n\n\nCreate instances by calling the class like a function. `__repr__` is generated automatically: field names appear in the output:\n\n::: {#56 .cell execution_count=26}\n``` {.python .cell-code}\nalice = StudentRecord(\"Alice Kamau\", 2024001, 3.95, \"Computer Science\")\nbob = StudentRecord(\"Bob Mwangi\", 2024002, 3.45)  # uses default major\n\nprint(alice)\nprint(bob)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStudentRecord(name='Alice Kamau', student_id=2024001, gpa=3.95, major='Computer Science')\nStudentRecord(name='Bob Mwangi', student_id=2024002, gpa=3.45, major='Undeclared')\n```\n:::\n:::\n\n\nAccess fields by name for readability or by index for tuple-compatible tools.\n`_replace()` returns a **new** record with selected fields updated. The original\nis immutable and unchanged:\n\n::: {#58 .cell execution_count=27}\n``` {.python .cell-code}\n# Access by name (readable) or by index (tuple-compatible)\nprint(f\"{alice.name}, GPA: {alice.gpa}\")\nprint(f\"By index alice[2]: {alice[2]}\")\n\n# _replace() creates a new record with selected fields changed\nalice_updated = alice._replace(gpa=3.97)\nprint(f\"Updated: {alice_updated}\")\n\n# NamedTuples unpack just like plain tuples\nname, sid, gpa, major = alice\nprint(f\"Unpacked: {name}, {major}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAlice Kamau, GPA: 3.95\nBy index alice[2]: 3.95\nUpdated: StudentRecord(name='Alice Kamau', student_id=2024001, gpa=3.97, major='Computer Science')\nUnpacked: Alice Kamau, Computer Science\n```\n:::\n:::\n\n\n## 5. Collections: Dict\n\nA **dictionary** (`dict`) maps unique **keys** to **values**.\nThink of it as a lookup table: given a key, you get back its associated value\nin O(1) time: instantly, regardless of how many entries the dict contains.\n\nUnlike a list (where you access items by numeric position), a dict lets you access\ndata by a meaningful label:\n\n```python\nstudent = {'name': 'Alice', 'gpa': 3.95, 'enrolled': True}\nstudent['gpa']       # 3.95  - by label, not by position\nstudent.get('age')   # None  - safe access, no KeyError\n```\n\n**When to use a dict:**\n- Access by name: student record, model config, API response payload\n- Counting occurrences: `{'cat': 3, 'dog': 1, 'bird': 2}`\n- Grouping: `{course_id: [student, student, ...]}`\n\nPython 3.7+ dicts preserve **insertion order**: you get keys back in the order\nyou added them.\n\n**Key operations at a glance:**\n\n| Operation | Syntax | Notes |\n|---|---|---|\n| Access | `d[key]` | Raises `KeyError` if key is missing |\n| Safe access | `d.get(key, default)` | Returns `default` (or `None`) if key missing |\n| Add / update | `d[key] = value` | Creates key if absent; overwrites if present |\n| Bulk update | `d.update(other)` | Merge another dict or iterable of pairs |\n| Remove | `d.pop(key)` | Remove and return value; `KeyError` if absent |\n| Remove (safe) | `d.pop(key, default)` | Returns `default` instead of raising |\n| Delete | `del d[key]` | Remove key in place; no return value |\n| Clear | `d.clear()` | Remove all pairs; dict remains (now empty) |\n| Membership | `key in d` | Checks keys only, O(1) |\n| Keys | `d.keys()` | Live view of all keys |\n| Values | `d.values()` | Live view of all values |\n| Pairs | `d.items()` | Live view of `(key, value)` tuples, used in `for` loops |\n| Length | `len(d)` | Number of key-value pairs |\n| Merge (3.9+) | `a \\| b` | New merged dict; right side wins on conflicts |\n| Merge in-place | `a \\|= b` | Update `a` with `b` in place |\n| Copy | `d.copy()` | Shallow independent copy |\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Key-Value Map</span><br><br>\nA <code>dict</code> maps unique, hashable keys to values.\nInsertion order is preserved (Python 3.7+).\nUse <code>dict[str, float]</code> to annotate key and value types.<br><br>\n<code>TypedDict</code> (Python 3.8+) defines a typed schema for a dict, essential for\nmodel configs and API payloads where every key and its type must be known.\n</div>\n\n::: {#60 .cell execution_count=28}\n``` {.python .cell-code}\n# Course record as a dict\ncourse: dict[str, object] = {\n    \"code\": \"CS301\",\n    \"title\": \"Machine Learning\",\n    \"credits\": 3,\n    \"enrollment\": 42,\n    \"pass_rate\": 0.87,\n}\n\n# Access: [] raises KeyError on missing key; .get() returns a default\nprint(course[\"title\"])\nprint(course.get(\"lab_room\", \"TBA\"))\n\n# Membership checks keys\nprint(f'\"pass_rate\" in course  : {\"pass_rate\" in course}')\nprint(f'\"semester\" in course   : {\"semester\" in course}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMachine Learning\nTBA\n\"pass_rate\" in course  : True\n\"semester\" in course   : False\n```\n:::\n:::\n\n\n### Modifying a Dict\n\nDicts are **mutable**: you can add, change, and remove keys after creation.\n`.pop()` removes a key and returns its value. `.items()` gives `(key, value)` pairs\nfor iteration *(for loops are covered in Sec. 10)*:\n\n::: {#62 .cell execution_count=29}\n``` {.python .cell-code}\n# Add / update / remove\ncourse[\"lab_room\"] = \"Lab 3A\"\ncourse.update({\"enrollment\": 45, \"semester\": \"Fall 2024\"})\nsemester = course.pop(\"semester\")  # remove and return\n\n# Iterate over all key-value pairs\nfor key, value in course.items():\n    print(f\"  {key:<12} : {value}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  code         : CS301\n  title        : Machine Learning\n  credits      : 3\n  enrollment   : 45\n  pass_rate    : 0.87\n  lab_room     : Lab 3A\n```\n:::\n:::\n\n\n### Dict Merge (Python 3.9+)\n`a | b` creates a **new** merged dict; the right-hand side wins on key conflicts.\n`a |= b` merges `b` into `a` in place. This replaces the older `{**a, **b}` pattern:\n\n::: {#64 .cell execution_count=30}\n``` {.python .cell-code}\n# Python 3.9+ dict merge operator | and |=\n# Replaces the older {**a, **b} pattern: cleaner and faster\n\ndefault_config: dict[str, object] = {\n    \"learning_rate\": 0.001,\n    \"epochs\": 10,\n    \"batch_size\": 32,\n    \"optimizer\": \"adam\",\n}\n\nrun_overrides: dict[str, object] = {\n    \"epochs\": 50,  # override\n    \"batch_size\": 64,  # override\n    \"dropout\": 0.2,  # new key\n}\n\n# | creates a NEW merged dict; right side wins on key conflicts\nrun_config = default_config | run_overrides\nprint(\"Merged run config:\")\nfor k, v in run_config.items():\n    print(f\"  {k:<16}: {v}\")\n\n# |= updates the dict in place\ndefault_config |= {\"weight_decay\": 1e-4}\nprint(f\"\\ndefault_config after |=: {default_config}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMerged run config:\n  learning_rate   : 0.001\n  epochs          : 50\n  batch_size      : 64\n  optimizer       : adam\n  dropout         : 0.2\n\ndefault_config after |=: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32, 'optimizer': 'adam', 'weight_decay': 0.0001}\n```\n:::\n:::\n\n\n### TypedDict: Typed Schema for a Dict\n`TypedDict` defines which keys a dict must have and the type of each value.\nIt uses `class` syntax (see section header note). At runtime it is a plain `dict`\nwith zero overhead. The schema is enforced only by the type checker:\n\n::: {#66 .cell execution_count=31}\n``` {.python .cell-code}\nfrom typing import TypedDict\n\n\nclass ModelConfig(TypedDict):\n    learning_rate: float\n    epochs: int\n    batch_size: int\n    optimizer: str\n\n\nclass ExperimentResult(TypedDict):\n    run_id: str\n    accuracy: float\n    val_loss: float\n```\n:::\n\n\nAnnotate a variable with your `TypedDict` class. The type checker flags wrong key names\nor value types. `type(config)` at runtime confirms it is simply a `dict`:\n\n::: {#68 .cell execution_count=32}\n``` {.python .cell-code}\n# TypedDict is a plain dict at runtime: no overhead\n# ty checks that keys and value types match the schema\nconfig: ModelConfig = {\n    \"learning_rate\": 0.001,\n    \"epochs\": 50,\n    \"batch_size\": 32,\n    \"optimizer\": \"adam\",\n}\n\nresult: ExperimentResult = {\n    \"run_id\": \"exp-2024-001\",\n    \"accuracy\": 0.923,\n    \"val_loss\": 0.218,\n}\n\nprint(f\"Config : {config}\")\nprint(f\"Result : {result}\")\nprint(f\"Accuracy: {result['accuracy']:.1%}\")\nprint(f\"type(config): {type(config)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nConfig : {'learning_rate': 0.001, 'epochs': 50, 'batch_size': 32, 'optimizer': 'adam'}\nResult : {'run_id': 'exp-2024-001', 'accuracy': 0.923, 'val_loss': 0.218}\nAccuracy: 92.3%\ntype(config): <class 'dict'>\n```\n:::\n:::\n\n\n<div style='background:#FFF1E6;border-left:5px solid #EA580C;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#9A3412;font-weight:bold'><i class=\"bi bi-puzzle-fill\"></i> Activity 4 - Merge Experiment Configs</span><br><br>\n<b>Goal:</b> Use the <code>|</code> operator to produce a final run config where <code>overrides</code> wins on conflicts, then add a <code>run_id</code> key.\n<pre style='background:#FCE8DA;padding:10px;border-radius:4px;font-size:0.9em'>base = {'lr': 0.01, 'epochs': 5, 'optimizer': 'sgd'}\noverrides = {'lr': 0.001, 'epochs': 20}\n\n# Expected\nfinal = {'lr': 0.001, 'epochs': 20, 'optimizer': 'sgd', 'run_id': 'run-001'}</pre>\n</div>\n\n::: {#70 .cell execution_count=33}\n``` {.python .cell-code}\nbase: dict[str, object] = {\"lr\": 0.01, \"epochs\": 5, \"optimizer\": \"sgd\"}\noverrides: dict[str, object] = {\"lr\": 0.001, \"epochs\": 20}\n\n# TODO: merge and add run_id\nfinal: dict[str, object] = ...\nprint(f\"final: {final}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfinal: Ellipsis\n```\n:::\n:::\n\n\n## 6. Collections: Set\n\nA **set** is an **unordered** collection of **unique** values.\nDuplicates are discarded automatically. You never need to deduplicate manually.\n\nTwo properties make sets special:\n\n1. **Uniqueness**: every value appears at most once, always\n2. **O(1) membership testing**: `x in my_set` takes the same time whether the set\n   has 10 or 10,000,000 items. The equivalent `x in my_list` slows down linearly.\n\n**When to use a set:**\n- Removing duplicates from a list: `unique = set(my_list)`\n- Fast membership check: `if label in valid_labels:`\n- Data pipeline integrity: find overlap or difference between train/val/test IDs\n\n**Key operations at a glance:**\n\n| Operation | Syntax / Method | Notes |\n|---|---|---|\n| Create | `{1, 2, 3}` or `set(iterable)` | `{}` creates a **dict**, use `set()` for empty |\n| Add | `s.add(x)` | No effect if `x` already present |\n| Remove | `s.remove(x)` | Raises `KeyError` if `x` absent |\n| Remove (safe) | `s.discard(x)` | No error if `x` absent |\n| Pop | `s.pop()` | Remove and return an arbitrary element |\n| Clear | `s.clear()` | Remove all elements |\n| Membership | `x in s` | O(1), instant regardless of set size |\n| Length | `len(s)` | Number of elements |\n| Union | `s \\| t` or `s.union(t)` | All elements from both sets |\n| Intersection | `s & t` or `s.intersection(t)` | Elements present in both |\n| Difference | `s - t` or `s.difference(t)` | In `s` but not in `t` |\n| Symmetric diff | `s ^ t` or `s.symmetric_difference(t)` | In one but not both |\n| Subset | `s <= t` or `s.issubset(t)` | Every element of `s` is in `t` |\n| Superset | `s >= t` or `s.issuperset(t)` | Every element of `t` is in `s` |\n| Disjoint | `s.isdisjoint(t)` | No elements in common |\n| Immutable copy | `frozenset(s)` | Immutable set, can be used as a dict key |\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Unique Values &amp; O(1) Lookup</span><br><br>\nA <code>set</code> never stores duplicates and tests membership in constant time.\nAnnotate as <code>set[str]</code>. For an immutable, hashable set that can be used as a\ndict key, use <code>frozenset</code>.\n</div>\n\n<div style='background:#FEF2F2;border-left:5px solid #DC2626;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#991B1B;font-weight:bold'><i class=\"bi bi-bug-fill\"></i> Common Mistake: {} Is a Dict, Not a Set</span><br><br>\n<code>empty = {}</code> creates an empty <b>dict</b>.<br>\n<code>empty = set()</code> creates an empty <b>set</b>.<br>\nThis trips up nearly every Python learner once. Now you know.\n</div>\n\n::: {#72 .cell execution_count=34}\n``` {.python .cell-code}\n# Sets remove duplicates on creation\nraw_labels: list[str] = [\"cat\", \"dog\", \"cat\", \"bird\", \"dog\", \"cat\"]\nunique_labels: set[str] = set(raw_labels)\nprint(f\"raw    : {raw_labels}\")\nprint(f\"unique : {sorted(unique_labels)}\")\n\n# O(1) membership test: much faster than list for large collections\nvalid_formats: set[str] = {\"parquet\", \"csv\", \"json\", \"feather\"}\nprint(f\"parquet valid : {'parquet' in valid_formats}\")\nprint(f\"xlsx valid    : {'xlsx' in valid_formats}\")\n\n# Mutation\nvalid_formats.add(\"orc\")\nvalid_formats.discard(\"feather\")  # safe: no error if element is absent\nprint(f\"formats : {sorted(valid_formats)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nraw    : ['cat', 'dog', 'cat', 'bird', 'dog', 'cat']\nunique : ['bird', 'cat', 'dog']\nparquet valid : True\nxlsx valid    : False\nformats : ['csv', 'json', 'orc', 'parquet']\n```\n:::\n:::\n\n\nConfirm the `{}` gotcha by running this cell. The type output makes it unmistakable:\n\n::: {#74 .cell execution_count=35}\n``` {.python .cell-code}\n# GOTCHA: {} creates a dict, not a set: always use set() for an empty set\nempty_dict = {}\nempty_set = set()\nprint(f\"type({{}})   : {type(empty_dict)}\")\nprint(f\"type(set()) : {type(empty_set)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntype({})   : <class 'dict'>\ntype(set()) : <class 'set'>\n```\n:::\n:::\n\n\n### Set Algebra\nSets support mathematical operations directly with operators. These are invaluable for\ndata-pipeline integrity checks such as detecting train/validation leakage:\n\n::: {#76 .cell execution_count=36}\n``` {.python .cell-code}\n# Set algebra: very common in data pipeline checks\ntrain_ids: set[int] = {101, 102, 103, 104, 105, 106, 107, 108}\nval_ids: set[int] = {107, 108, 109, 110}\n\nprint(f\"Union        : {sorted(train_ids | val_ids)}\")\nprint(f\"Intersection : {sorted(train_ids & val_ids)}\")\nprint(f\"Difference   : {sorted(train_ids - val_ids)}\")\nprint(f\"Sym. diff    : {sorted(train_ids ^ val_ids)}\")\n\n# Practical: check for data leakage between splits\nleakage: set[int] = train_ids & val_ids\nif leakage:\n    print(f\"\\nWARNING: {len(leakage)} IDs in both train and val : data leakage! {leakage}\")\nelse:\n    print(\"\\nNo data leakage between splits.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUnion        : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]\nIntersection : [107, 108]\nDifference   : [101, 102, 103, 104, 105, 106]\nSym. diff    : [101, 102, 103, 104, 105, 106, 109, 110]\n\nWARNING: 2 IDs in both train and val : data leakage! {107, 108}\n```\n:::\n:::\n\n\n## 7. Standard Library Collections\n\nPython ships with a large collection of ready-to-use modules called the\n**standard library**: available without any `pip install`. The `collections` module\ncontains specialised containers that solve common data patterns more cleanly than plain\n`list` and `dict`.\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Specialised Containers from <code>collections</code></span><br><br>\nThree tools from the standard library cover the most common data-science patterns beyond the built-in types:\n<ul>\n<li><b>Counter</b>: count occurrences; perfect for label frequencies and class imbalance checks</li>\n<li><b>defaultdict</b>: group items without writing <code>if key not in d: d[key] = []</code></li>\n<li><b>deque</b>: O(1) append and pop from both ends; ideal for sliding windows in time series</li>\n</ul>\n</div>\n\n::: {#78 .cell execution_count=37}\n``` {.python .cell-code}\nfrom collections import Counter\n\n# Class imbalance check using Counter\npredicted_labels: list[str] = [\n    \"pass\",\n    \"pass\",\n    \"fail\",\n    \"pass\",\n    \"pass\",\n    \"fail\",\n    \"pass\",\n    \"pass\",\n    \"pass\",\n    \"fail\",\n    \"pass\",\n    \"pass\",\n]\n\ncounts: Counter[str] = Counter(predicted_labels)\nprint(f\"All counts : {counts}\")\nprint(f'\"pass\"     : {counts[\"pass\"]}')\nprint(f\"Unknown    : {counts['unknown']}\")  # returns 0, not KeyError\nprint(f\"Top 2      : {counts.most_common(2)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAll counts : Counter({'pass': 9, 'fail': 3})\n\"pass\"     : 9\nUnknown    : 0\nTop 2      : [('pass', 9), ('fail', 3)]\n```\n:::\n:::\n\n\nBuild a class-distribution report and combine counters from multiple batches using\nCounter arithmetic: `+` merges counts, `-` subtracts (removing zeros):\n\n::: {#80 .cell execution_count=38}\n``` {.python .cell-code}\n# Class distribution report\ntotal: int = sum(counts.values())\nfor label, n in counts.most_common():\n    print(f\"  {label:<8}: {n:2d}/{total} ({n / total:.1%})\")\n\n# Counter arithmetic: combine counts from multiple batches\nbatch_a: Counter[str] = Counter([\"pass\", \"pass\", \"fail\"])\nbatch_b: Counter[str] = Counter([\"fail\", \"fail\", \"pass\"])\ncombined = batch_a + batch_b\nprint(f\"\\nCombined batches: {combined}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  pass    :  9/12 (75.0%)\n  fail    :  3/12 (25.0%)\n\nCombined batches: Counter({'pass': 3, 'fail': 3})\n```\n:::\n:::\n\n\n<div style='background:#FFF1E6;border-left:5px solid #EA580C;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#9A3412;font-weight:bold'><i class=\"bi bi-puzzle-fill\"></i> Activity 5 - Label Frequency Report</span><br><br>\n<b>Goal:</b> Use <code>Counter</code> to produce a class distribution report from the labels list below.\n<pre style='background:#FCE8DA;padding:10px;border-radius:4px;font-size:0.9em'>labels = ['A','B','A','C','B','A','A','B','C','A','B','A']\n\n# Expected output\nA : 6/12 (50.0%)  [##############################]\nB : 4/12 (33.3%)  [####################          ]\nC : 2/12 (16.7%)  [##########                    ]</pre>\n<b>Hint:</b> Build the bar with <code>'#' * int(pct * 30)</code>.\n</div>\n\n::: {#82 .cell execution_count=39}\n``` {.python .cell-code}\nfrom collections import Counter\n\nlabels: list[str] = [\"A\", \"B\", \"A\", \"C\", \"B\", \"A\", \"A\", \"B\", \"C\", \"A\", \"B\", \"A\"]\n\n# TODO: print a class distribution report\ncounts: Counter[str] = Counter(labels)\ntotal: int = sum(counts.values())\n\nfor label, n in counts.most_common():\n    pct = n / total\n    bar = ...  # TODO: build the bar string\n    print(f\"{label} : {n}/{total} ({pct:.1%})  [{bar:<30}]\")\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-red-fg\">---------------------------------------------------------------------------</span>\n<span class=\"ansi-red-fg\">TypeError</span>                                 Traceback (most recent call last)\n<span class=\"ansi-cyan-fg\">Cell</span><span class=\"ansi-cyan-fg\"> </span><span class=\"ansi-green-fg\">In[39]</span><span class=\"ansi-green-fg\">, line 12</span>\n<span class=\"ansi-green-fg\">     10</span> pct = n / total\n<span class=\"ansi-green-fg\">     11</span> bar = ...  <span style=\"font-style:italic;color:rgb(95,135,135)\"># TODO: build the bar string</span>\n<span class=\"ansi-green-fg\">---&gt; </span><span class=\"ansi-green-fg\">12</span> <span style=\"color:rgb(0,135,0)\">print</span>(<span class=\"ansi-yellow-fg\">f</span><span class=\"ansi-yellow-fg\">\"</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span>label<span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\"> : </span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span>n<span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\">/</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span>total<span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\"> (</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">{</span>pct<span style=\"font-weight:bold;color:rgb(175,95,135)\">:</span><span class=\"ansi-yellow-fg\">.1%</span><span style=\"font-weight:bold;color:rgb(175,95,135)\">}</span><span class=\"ansi-yellow-fg\">)  [</span><span style=\"font-weight:bold;color:rgb(175,95,135)\" class=\"ansi-yellow-bg\">{</span><span class=\"ansi-yellow-bg\">bar</span><span style=\"font-weight:bold;color:rgb(175,95,135)\" class=\"ansi-yellow-bg\">:</span><span class=\"ansi-yellow-fg ansi-yellow-bg\">&lt;30</span><span style=\"font-weight:bold;color:rgb(175,95,135)\" class=\"ansi-yellow-bg\">}</span><span class=\"ansi-yellow-fg\">]</span><span class=\"ansi-yellow-fg\">\"</span>)\n\n<span class=\"ansi-red-fg\">TypeError</span>: unsupported format string passed to ellipsis.__format__</pre>\n```\n:::\n\n:::\n:::\n\n\n### defaultdict: Zero-Setup Grouping\n`defaultdict(factory)` calls `factory()` to create a new default value whenever a\nmissing key is accessed, eliminating the `if key not in d: d[key] = []` boilerplate.\n`defaultdict(list)` is the standard pattern for grouping *(uses a for loop, see Sec. 11)*:\n\n::: {#84 .cell execution_count=40}\n``` {.python .cell-code}\nfrom collections import defaultdict\n\nstudents: list[dict[str, object]] = [\n    {\"name\": \"Alice\", \"major\": \"CS\", \"gpa\": 3.95},\n    {\"name\": \"Bob\", \"major\": \"Math\", \"gpa\": 3.45},\n    {\"name\": \"Carol\", \"major\": \"CS\", \"gpa\": 3.88},\n    {\"name\": \"Dan\", \"major\": \"Math\", \"gpa\": 3.72},\n    {\"name\": \"Eve\", \"major\": \"CS\", \"gpa\": 3.60},\n]\n\n# Group students by major: no 'if key not in d: d[key] = []' needed\nby_major: defaultdict[str, list[str]] = defaultdict(list)\nfor s in students:\n    by_major[str(s[\"major\"])].append(str(s[\"name\"]))\n\nprint(\"Students by major:\")\nfor major, names in sorted(by_major.items()):\n    print(f\"  {major}: {names}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStudents by major:\n  CS: ['Alice', 'Carol', 'Eve']\n  Math: ['Bob', 'Dan']\n```\n:::\n:::\n\n\nThe same pattern works for numeric accumulation. `defaultdict(float)` starts every\nnew key at `0.0`, making sum-per-group pipelines one-liners:\n\n::: {#86 .cell execution_count=41}\n``` {.python .cell-code}\n# Accumulate GPA sums per major\ngpa_total: defaultdict[str, float] = defaultdict(float)\ngpa_count: defaultdict[str, int] = defaultdict(int)\n\nfor s in students:\n    key = str(s[\"major\"])\n    gpa_total[key] += float(s[\"gpa\"])  # type: ignore[arg-type]\n    gpa_count[key] += 1\n\nprint(\"Average GPA by major:\")\nfor major in sorted(gpa_total):\n    print(f\"  {major}: {gpa_total[major] / gpa_count[major]:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAverage GPA by major:\n  CS: 3.81\n  Math: 3.58\n```\n:::\n:::\n\n\n### deque: Fixed-Size Rolling Buffer\n`deque(maxlen=N)` discards the oldest element automatically when the buffer is full.\nThis is the standard tool for rolling statistics over time-series streams:\n\n::: {#88 .cell execution_count=42}\n``` {.python .cell-code}\nfrom collections import deque\n\n# Rolling mean with maxlen: oldest element auto-discards when full\ntemperature_readings: list[float] = [\n    36.5,\n    36.7,\n    37.1,\n    37.8,\n    38.2,\n    38.0,\n    37.5,\n    37.2,\n    36.9,\n    36.6,\n]\nWINDOW: int = 3\n\nwindow: deque[float] = deque(maxlen=WINDOW)\nrolling_means: list[float] = []\n\nfor reading in temperature_readings:\n    window.append(reading)\n    if len(window) == WINDOW:\n        rolling_means.append(round(sum(window) / WINDOW, 2))\n\nprint(f\"Readings      : {temperature_readings}\")\nprint(f\"Rolling mean-3: {rolling_means}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReadings      : [36.5, 36.7, 37.1, 37.8, 38.2, 38.0, 37.5, 37.2, 36.9, 36.6]\nRolling mean-3: [36.77, 37.2, 37.7, 38.0, 37.9, 37.57, 37.2, 36.9]\n```\n:::\n:::\n\n\nA `deque` doubles as a FIFO queue. `appendleft()` and `popleft()` are O(1) --\nfar faster than `list.insert(0, ...)` which is O(n):\n\n::: {#90 .cell execution_count=43}\n``` {.python .cell-code}\nfrom collections import deque\n\n# deque as a task queue: O(1) popleft vs list's O(n)\npipeline: deque[str] = deque([\"load_data\", \"clean\", \"feature_eng\", \"train\", \"evaluate\"])\npipeline.appendleft(\"validate_schema\")  # high-priority step prepended\n\nprint(\"Pipeline execution order:\")\nwhile pipeline:\n    step = pipeline.popleft()\n    print(f\"  -> {step}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPipeline execution order:\n  -> validate_schema\n  -> load_data\n  -> clean\n  -> feature_eng\n  -> train\n  -> evaluate\n```\n:::\n:::\n\n\n### statistics: Descriptive Stats Without NumPy\n\nThe `statistics` module computes common descriptive statistics on plain Python\nlists, no NumPy required. Use it for quick sanity checks and lightweight scripts.\nFor large arrays, NumPy is faster (covered in Part 3).\n\n::: {#92 .cell execution_count=44}\n``` {.python .cell-code}\nimport statistics\n\nexam_scores: list[float] = [72.0, 85.0, 91.0, 68.0, 88.0, 77.0, 94.0, 63.0]\n\nmean = statistics.mean(exam_scores)\nmedian = statistics.median(exam_scores)\nstdev = statistics.stdev(exam_scores)  # sample std deviation\npstdev = statistics.pstdev(exam_scores)  # population std deviation\nvar = statistics.variance(exam_scores)\n\nprint(f\"n      = {len(exam_scores)}\")\nprint(f\"mean   = {mean:.2f}\")\nprint(f\"median = {median:.2f}\")\nprint(f\"stdev  = {stdev:.2f}   (sample)\")\nprint(f\"var    = {var:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn      = 8\nmean   = 79.75\nmedian = 81.00\nstdev  = 11.41   (sample)\nvar    = 130.21\n```\n:::\n:::\n\n\nUse `statistics.NormalDist` to compute z-scores and check where any value falls in the distribution:\n\n::: {#94 .cell execution_count=45}\n``` {.python .cell-code}\nfrom statistics import NormalDist\n\ndist = NormalDist(mu=mean, sigma=stdev)\n\nfor score in [63.0, 77.0, 94.0]:\n    z = (score - mean) / stdev\n    pct = dist.cdf(score) * 100  # percentile rank\n    print(f\"  score={score:5.1f}  z={z:+.2f}  percentile={pct:.1f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  score= 63.0  z=-1.47  percentile=7.1%\n  score= 77.0  z=-0.24  percentile=40.5%\n  score= 94.0  z=+1.25  percentile=89.4%\n```\n:::\n:::\n\n\n## 8. Operators\n\nAn **operator** is a symbol that performs a computation on one or two values.\nYou already know arithmetic operators from mathematics. Python adds several more:\n\n| Category | Operators | Example |\n|---|---|---|\n| Arithmetic | `+` `-` `*` `/` `//` `%` `**` | `7 // 2` → `3` |\n| Comparison | `==` `!=` `<` `>` `<=` `>=` | `score >= 70` → `True` |\n| Logical | `and` `or` `not` | `a and b` |\n| Assignment expression | `:=` (walrus) | `if (n := len(data)) > 10:` |\n\nThree operator families matter most in data science work: **arithmetic**, **comparison + logical**, and the **walrus** `:=` (Python 3.8+).\n\n::: {#96 .cell execution_count=46}\n``` {.python .cell-code}\n# Weighted grade calculation\nmidterm: float = 82.0\nfinal: float = 91.0\nproject: float = 88.0\n\nweighted_grade = midterm * 0.30 + final * 0.50 + project * 0.20\nprint(f\"Weighted grade: {weighted_grade:.1f}\")\n\n# Augmented assignment modifies in place\nloss: float = 1.0\nfor _ in range(6):\n    loss *= 0.75\nprint(f\"Loss after 6 decay steps: {loss:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWeighted grade: 87.7\nLoss after 6 decay steps: 0.1780\n```\n:::\n:::\n\n\n`/` and `//` are **different operators**. This is one of the most common Python gotchas:\n`//` floors toward negative infinity, not toward zero:\n\n::: {#98 .cell execution_count=47}\n``` {.python .cell-code}\n# Division: / is always true division; // is floor (rounds toward -inf)\nprint(f\"7 / 2  = {7 / 2}\")  # 3.5 : always float\nprint(f\"7 // 2 = {7 // 2}\")  # 3   : floor, not truncate\nprint(f\"7 % 2  = {7 % 2}\")  # 1   : remainder\nprint(f\"2**10  = {2**10}\")  # 1024: exponentiation\nprint(f\"-7//2  = {-7 // 2}\")  # -4  : floors TOWARD negative infinity\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n7 / 2  = 3.5\n7 // 2 = 3\n7 % 2  = 1\n2**10  = 1024\n-7//2  = -4\n```\n:::\n:::\n\n\n### Comparison & Logical Operators\nComparison operators return `bool`. Logical operators combine conditions and use\n**short-circuit** evaluation: the right side is not evaluated if the left side\nalready determines the result:\n\n::: {#100 .cell execution_count=48}\n``` {.python .cell-code}\n# Comparison and logical operators\nscore: float = 84.5\nattendance: int = 90\n\npasses = score >= 70\nqualifies = score >= 80 and attendance >= 85  # both must be true\nat_risk = score < 60 or attendance < 70  # either triggers\nnot_pass = not passes\n\nprint(f\"{passes=}  {qualifies=}  {at_risk=}  {not_pass=}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npasses=True  qualifies=True  at_risk=False  not_pass=False\n```\n:::\n:::\n\n\nShort-circuit evaluation prevents errors like dividing by an empty list.\nUse `is`/`is not` to check **object identity** (same object in memory) and\n`==`/`!=` to check **value equality**:\n\n::: {#102 .cell execution_count=49}\n``` {.python .cell-code}\n# Short-circuit evaluation: right side is NOT evaluated if left decides outcome\nscores: list[float] | None = [82.0, 91.5, 74.0]\nmean = scores and sum(scores) / len(scores)  # safe: skips divide if scores is None\nprint(f\"mean (safe): {mean}\")\n\n# Identity (is) vs equality (==)\na: list[int] = [1, 2, 3]\nb: list[int] = [1, 2, 3]\nc: list[int] = a\nprint(f\"a == b : {a == b}\")  # True : same values\nprint(f\"a is b : {a is b}\")  # False: different objects\nprint(f\"a is c : {a is c}\")  # True : same object\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmean (safe): 82.5\na == b : True\na is b : False\na is c : True\n```\n:::\n:::\n\n\n### Walrus Operator `:=` (Python 3.8+)\n`:=` is an **assignment expression**: unlike `=` (a statement), it both assigns\na value and evaluates to that value. This lets you assign inside a condition,\navoiding computing the same value twice:\n\n::: {#104 .cell execution_count=50}\n``` {.python .cell-code}\n# Walrus operator := (Python 3.8+)\n# Assigns AND returns a value in the same expression.\nexam_scores: list[float] = [82.0, 91.5, 74.0, 88.0, 95.5, 64.0, 79.0]\n\n# Without walrus: must store mean manually before using in condition\nm = sum(exam_scores) / len(exam_scores)\nif m < 80:\n    print(f\"[without walrus] Cohort average is low: {m:.1f}\")\n\n# With walrus: compute once, test, and use: all in one expression\nif (m := sum(exam_scores) / len(exam_scores)) < 80:\n    print(f\"[with walrus]    Cohort average is low: {m:.1f}\")\n```\n:::\n\n\n`:=` is especially useful inside `while` loops that consume a stream and inside\ncomprehensions that need to reuse a computed intermediate value:\n\n::: {#106 .cell execution_count=51}\n``` {.python .cell-code}\n# Walrus in a while loop: consume a stream until None sentinel\ndata_stream = iter([10.0, 20.0, 30.0, None, 40.0])\nwhile (value := next(data_stream, None)) is not None:\n    print(f\"  Read: {value}\")\n\n# Walrus in a comprehension: strip once, reuse stripped value\nraw_names: list[str] = [\"  Alice  \", \"\", \"  Bob  \", \" \", \"  Carol  \"]\nclean_names: list[str] = [stripped for name in raw_names if (stripped := name.strip())]\nprint(f\"Clean names: {clean_names}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Read: 10.0\n  Read: 20.0\n  Read: 30.0\nClean names: ['Alice', 'Bob', 'Carol']\n```\n:::\n:::\n\n\n## 9. Control Flow: if / elif / else & match / case\n\nSo far every cell runs its lines from top to bottom, once, in order.\n**Control flow** lets you change that:\n- `if / elif / else`: run one branch based on a condition\n- `match / case`: route structured data to different handlers (Python 3.10+)\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: match / case (Python 3.10+)</span><br><br>\nStructural pattern matching goes beyond simple equality checks.\nIt can match on the <b>shape of data</b>, destructuring dicts, lists, and class instances in the same step.\nUse it when branching on the shape or value of structured data, not just numeric thresholds.\n</div>\n\n::: {#108 .cell execution_count=52}\n``` {.python .cell-code}\ndef classify_grade(score: float) -> str:\n    \"\"\"Return letter grade for a numeric score.\"\"\"\n    if score >= 90:\n        return \"A: Excellent\"\n    elif score >= 80:\n        return \"B: Good\"\n    elif score >= 70:\n        return \"C: Satisfactory\"\n    elif score >= 60:\n        return \"D: Needs improvement\"\n    else:\n        return \"F: See instructor\"\n```\n:::\n\n\nTest the function across the full grade range:\n\n::: {#110 .cell execution_count=53}\n``` {.python .cell-code}\nfor s in [95.0, 83.5, 71.0, 62.0, 45.0]:\n    print(f\"  {s:5.1f} -> {classify_grade(s)}\")\n\n# Ternary expression: one-liner for simple binary choices\nscore = 87.0\nstatus = \"pass\" if score >= 70 else \"fail\"\nband = \"high\" if score >= 90 else (\"mid\" if score >= 70 else \"low\")\nprint(f\"\\n{score} -> {status}, {band}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   95.0 -> A: Excellent\n   83.5 -> B: Good\n   71.0 -> C: Satisfactory\n   62.0 -> D: Needs improvement\n   45.0 -> F: See instructor\n\n87.0 -> pass, mid\n```\n:::\n:::\n\n\n### match / case: Structural Pattern Matching (Python 3.10+)\n`match` goes beyond simple equality checks. It can destructure **the shape of data**,\nextracting values from dicts and lists in one step. Define the routing function first:\n\n::: {#112 .cell execution_count=54}\n``` {.python .cell-code}\n# match / case: structural pattern matching (Python 3.10+)\ndef process_event(event: dict[str, object]) -> str:\n    \"\"\"Route a training event to the right handler.\"\"\"\n    match event:\n        case {\"type\": \"epoch\", \"epoch\": e, \"loss\": l} if float(str(l)) < 0.05:\n            return f\"Epoch {e}: converged (loss={l:.3f})\"\n        case {\"type\": \"epoch\", \"epoch\": e, \"loss\": l}:\n            return f\"Epoch {e}: loss={l:.3f}\"\n        case {\"type\": \"error\", \"message\": msg}:\n            return f\"ERROR: {msg}\"\n        case {\"type\": t}:\n            return f\"Unhandled event type: {t!r}\"\n        case _:\n            return \"Malformed event\"\n```\n:::\n\n\nRun a variety of event shapes through the dispatcher to see each `case` arm triggered.\nThe `case _:` arm is a catch-all that always matches:\n\n::: {#114 .cell execution_count=55}\n``` {.python .cell-code}\nevents: list[dict[str, object]] = [\n    {\"type\": \"epoch\", \"epoch\": 1, \"loss\": 0.823},\n    {\"type\": \"epoch\", \"epoch\": 20, \"loss\": 0.041},\n    {\"type\": \"error\", \"message\": \"OOM on GPU 0\"},\n    {\"type\": \"checkpoint\"},\n    {\"status\": \"idle\"},\n]\n\nfor ev in events:\n    print(process_event(ev))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEpoch 1: loss=0.823\nEpoch 20: converged (loss=0.041)\nERROR: OOM on GPU 0\nUnhandled event type: 'checkpoint'\nMalformed event\n```\n:::\n:::\n\n\n<div style='background:#FFF1E6;border-left:5px solid #EA580C;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#9A3412;font-weight:bold'><i class=\"bi bi-puzzle-fill\"></i> Activity 6 - Match on HTTP-style Status Codes</span><br><br>\n<b>Goal:</b> Write a <code>describe_status(code)</code> function using <code>match/case</code> that returns a short description.\n<pre style='background:#FCE8DA;padding:10px;border-radius:4px;font-size:0.9em'>describe_status(200)  -> '200 OK'\ndescribe_status(404)  -> '404 Not Found'\ndescribe_status(500)  -> '500 Server Error'\ndescribe_status(301)  -> '3xx Redirect'\ndescribe_status(999)  -> 'Unknown code'</pre>\n<b>Hint:</b> Use <code>case 2xx</code> patterns are not valid. Use guard conditions instead: <code>case c if 200 <= c < 300</code>.\n</div>\n\n::: {#116 .cell execution_count=56}\n``` {.python .cell-code}\ndef describe_status(code: int) -> str:\n    \"\"\"Return a short description for an HTTP-style status code.\"\"\"\n    match code:\n        case _:\n            return \"unknown\"  # TODO: replace with specific case patterns\n\n\nfor c in [200, 404, 500, 301, 999]:\n    print(describe_status(c))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nunknown\nunknown\nunknown\nunknown\nunknown\n```\n:::\n:::\n\n\n## 10. Control Flow: for Loops\n\nA **`for` loop** repeats a block of code once for each item in a collection.\nIt is the primary tool for processing datasets, running training epochs, and\niterating over files.\n\n```python\nfor score in [78, 85, 92]:   # repeat once per score\n    print(score)              # output: 78, then 85, then 92\n```\n\nThe indented block (4 spaces) is the **loop body**: it runs once per item.\n\nPython `for` loops iterate over any **iterable**. The built-ins `range()`, `enumerate()`, and `zip()` cover the most common patterns in data work.\n\n::: {#118 .cell execution_count=57}\n``` {.python .cell-code}\n# range(start, stop, step): generates integers lazily (no list in memory)\nMAX_EPOCHS: int = 5\nloss: float = 1.0\n\nfor epoch in range(1, MAX_EPOCHS + 1):\n    loss *= 0.75\n    print(f\"  Epoch {epoch}/{MAX_EPOCHS}  loss={loss:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Epoch 1/5  loss=0.7500\n  Epoch 2/5  loss=0.5625\n  Epoch 3/5  loss=0.4219\n  Epoch 4/5  loss=0.3164\n  Epoch 5/5  loss=0.2373\n```\n:::\n:::\n\n\n`enumerate()` pairs each element with its index, counting from `start=1` by default\n(or any integer you choose), eliminating the need for manual `i += 1` counters:\n\n::: {#120 .cell execution_count=58}\n``` {.python .cell-code}\n# enumerate(): loop with automatic index; avoids manual counter variables\nstudents: list[str] = [\"Alice\", \"Carol\", \"Dan\", \"Bob\"]\n\nprint(\"Leaderboard:\")\nfor rank, name in enumerate(students, start=1):\n    print(f\"  #{rank}  {name}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLeaderboard:\n  #1  Alice\n  #2  Carol\n  #3  Dan\n  #4  Bob\n```\n:::\n:::\n\n\n`zip()` stitches two or more iterables together element-by-element. Pairs stop when\nthe **shortest** input is exhausted. Build a `dict` from two parallel lists using\n`dict(zip(keys, values))`:\n\n::: {#122 .cell execution_count=59}\n``` {.python .cell-code}\n# zip(): iterate two or more iterables in lockstep\n# strict=True raises ValueError if the iterables have different lengths\nnames: list[str] = [\"Alice\", \"Bob\", \"Carol\"]\nscores: list[float] = [92.0, 74.5, 88.0]\n\nprint(\"Score sheet:\")\nfor name, score in zip(names, scores, strict=True):\n    grade = \"pass\" if score >= 70 else \"fail\"\n    print(f\"  {name:<8} {score:5.1f}  {grade}\")\n\n# Build a dict from two parallel lists\nmetric_names: list[str] = [\"accuracy\", \"precision\", \"recall\"]\nmetric_vals: list[float] = [0.923, 0.911, 0.934]\nreport: dict[str, float] = dict(zip(metric_names, metric_vals, strict=True))\nprint()\nprint(f\"Report: {report}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nScore sheet:\n  Alice     92.0  pass\n  Bob       74.5  pass\n  Carol     88.0  pass\n\nReport: {'accuracy': 0.923, 'precision': 0.911, 'recall': 0.934}\n```\n:::\n:::\n\n\n### tqdm: Progress Bars for Long Loops\n\nWhen a loop processes thousands of files or training examples, you need to know\nhow long it will take. `tqdm` wraps any iterable and displays a live progress bar\nwith elapsed time, rate, and ETA, with zero code changes to the loop body:\n\n```python\npip install tqdm   # if not already installed\n```\n\n::: {#124 .cell execution_count=60}\n``` {.python .cell-code}\nfrom tqdm import tqdm\n\n# Wrap any iterable with tqdm() - the loop body is unchanged\nscores: list[float] = []\nfor i in tqdm(range(1_000), desc=\"Simulating scores\", unit=\"rec\"):\n    scores.append(50 + (i % 50))  # dummy computation\n\nprint(f\"Generated {len(scores)} scores, mean = {sum(scores) / len(scores):.1f}\")\n\n# tqdm also works with enumerate and zip\nlabels: list[str] = [\"pass\" if s >= 70 else \"fail\" for s in tqdm(scores, desc=\"Labelling\", leave=False)]\nprint(f\"pass rate: {labels.count('pass') / len(labels):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGenerated 1000 scores, mean = 74.5\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\npass rate: 60.0%\n```\n:::\n:::\n\n\n## 11. Control Flow: while, break, continue\n\nA **`while` loop** repeats a block as long as a condition is `True`. Unlike `for`\n(which iterates a fixed collection), `while` runs an **indefinite** number of times\nuntil either the condition becomes `False` or a `break` statement is hit.\n\n```python\nloss = 1.0\nwhile loss > 0.05:    # keep running until loss is small enough\n    loss *= 0.7       # shrink loss by 30% each iteration\n```\n\nUse `while` when you do not know in advance how many iterations are needed: waiting for convergence, retrying a failing operation, or consuming a data stream.\n\n- `break`: exit the loop immediately\n- `continue`: skip the rest of this iteration\n- `else` on a loop: runs **only** if no `break` was hit\n\n::: {#126 .cell execution_count=61}\n``` {.python .cell-code}\n# while: train until convergence or budget exhausted\nloss: float = 1.0\nepoch: int = 0\nMAX_EPOCHS: int = 30\nTHRESHOLD: float = 0.05\n\nwhile loss > THRESHOLD and epoch < MAX_EPOCHS:\n    loss *= 0.7\n    epoch += 1\n\nprint(f\"Stopped at epoch {epoch}: loss={loss:.4f}\")\nprint(f\"Converged: {loss <= THRESHOLD}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStopped at epoch 9: loss=0.0404\nConverged: True\n```\n:::\n:::\n\n\n### break and continue\n`break` exits the innermost loop immediately. Use it when a sentinel value or error\ncondition means further iteration is pointless:\n\n::: {#128 .cell execution_count=62}\n``` {.python .cell-code}\n# break: exit the loop immediately when a sentinel is found\nreadings: list[float | None] = [36.5, 36.9, 37.4, None, 38.1, 37.8]\nclean: list[float] = []\n\nfor r in readings:\n    if r is None:\n        print(\"Sensor error : stopping collection\")\n        break\n    clean.append(r)\n\nprint(f\"Clean readings: {clean}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSensor error : stopping collection\nClean readings: [36.5, 36.9, 37.4]\n```\n:::\n:::\n\n\n`continue` skips the rest of the current iteration and jumps to the next one. Ideal\nfor filtering bad data without a nested `if/else`. The `else` clause on a loop runs\nonly if no `break` occurred:\n\n::: {#130 .cell execution_count=63}\n``` {.python .cell-code}\n# continue: skip the rest of this iteration and move to the next\nraw: list[object] = [85.0, \"n/a\", None, 92.0, \"\", 78.5, -1.0, 95.0]\nvalid: list[float] = []\n\nfor item in raw:\n    if not isinstance(item, int | float) or float(str(item)) < 0:\n        continue  # skip bad items\n    valid.append(float(str(item)))\n\nprint(f\"Valid scores: {valid}\")\n\n# loop else: runs only when the loop was NOT exited via break\nrequired_fields: list[str] = [\"name\", \"gpa\", \"major\"]\nrecord: dict[str, str] = {\"name\": \"Alice\", \"gpa\": \"3.95\", \"major\": \"CS\"}\n\nfor field in required_fields:\n    if field not in record:\n        print(f\"Missing required field: {field!r}\")\n        break\nelse:\n    print(\"All required fields present\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nValid scores: [85.0, 92.0, 78.5, 95.0]\nAll required fields present\n```\n:::\n:::\n\n\n## 12. Comprehensions\n\nA **comprehension** builds a new collection by transforming or filtering an existing\none, all in a single expression. It replaces the verbose `for` + `.append()` pattern:\n\n```python\n# Loop version (3 lines):\nsquares = []\nfor n in range(5):\n    squares.append(n ** 2)   # [0, 1, 4, 9, 16]\n\n# Comprehension (1 line, identical result):\nsquares = [n ** 2 for n in range(5)]\n```\n\nComprehensions are faster than equivalent loops and are considered idiomatic Python.\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> Key Concept: Concise, Readable Collection Construction</span><br><br>\nComprehensions build new collections by <b>transforming or filtering</b> an iterable in a single expression.\nThey are faster than equivalent <code>for</code> + <code>.append()</code> loops and are idiomatic Python.\n\n<table style='margin-top:8px;border-collapse:collapse'>\n<tr><td style='padding:4px 12px;font-family:monospace'>[expr for x in it if cond]</td><td style='padding:4px 12px'>list</td></tr>\n<tr><td style='padding:4px 12px;font-family:monospace'>{k: v for x in it if cond}</td><td style='padding:4px 12px'>dict</td></tr>\n<tr><td style='padding:4px 12px;font-family:monospace'>{expr for x in it if cond}</td><td style='padding:4px 12px'>set</td></tr>\n<tr><td style='padding:4px 12px;font-family:monospace'>(expr for x in it if cond)</td><td style='padding:4px 12px'>generator (lazy, no list in memory)</td></tr>\n</table>\n</div>\n\n::: {#132 .cell execution_count=64}\n``` {.python .cell-code}\nraw_scores: list[float] = [78.0, 85.5, 92.0, 88.5, 95.0, 67.0, 81.0]\n\n# Transform: min-max normalise to [0, 1]\nlo, hi = min(raw_scores), max(raw_scores)\nnormed: list[float] = [(s - lo) / (hi - lo) for s in raw_scores]\nprint(f\"Normalised: {[round(n, 2) for n in normed]}\")\n\n# Filter: keep only passing scores\npassing: list[float] = [s for s in raw_scores if s >= 70]\nprint(f\"Passing   : {passing}\")\n\n# Filter + transform: label each score\nlabels: list[str] = [f\"{s:.0f} (pass)\" if s >= 70 else f\"{s:.0f} (FAIL)\" for s in raw_scores]\nprint(f\"Labelled  : {labels}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNormalised: [0.39, 0.66, 0.89, 0.77, 1.0, 0.0, 0.5]\nPassing   : [78.0, 85.5, 92.0, 88.5, 95.0, 81.0]\nLabelled  : ['78 (pass)', '86 (pass)', '92 (pass)', '88 (pass)', '95 (pass)', '67 (FAIL)', '81 (pass)']\n```\n:::\n:::\n\n\nA two-clause comprehension flattens a nested collection. Read\n`[s for batch in batches for s in batch]` left-to-right:\n\"outer loop, inner loop, collect `s`\":\n\n::: {#134 .cell execution_count=65}\n``` {.python .cell-code}\n# Flatten a nested structure with a two-clause comprehension\nbatches: list[list[float]] = [[85.0, 91.0], [74.0, 88.5], [95.0, 79.0]]\nflat: list[float] = [s for batch in batches for s in batch]\nprint(f\"Flattened : {flat}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFlattened : [85.0, 91.0, 74.0, 88.5, 95.0, 79.0]\n```\n:::\n:::\n\n\n### Dict, Set, and Generator Comprehensions\nThe `[...]` syntax extends to dicts (`{k: v for ...}`), sets (`{expr for ...}`),\nand lazy generators (`(expr for ...)`):\n\n::: {#136 .cell execution_count=66}\n``` {.python .cell-code}\nstudents: list[dict[str, object]] = [\n    {\"name\": \"Alice\", \"score\": 92.0, \"major\": \"CS\"},\n    {\"name\": \"Bob\", \"score\": 74.5, \"major\": \"Math\"},\n    {\"name\": \"Carol\", \"score\": 88.0, \"major\": \"CS\"},\n    {\"name\": \"Dan\", \"score\": 61.0, \"major\": \"Physics\"},\n]\n\n# Dict comprehension: build a name -> score lookup\nscore_lookup: dict[str, float] = {str(s[\"name\"]): float(str(s[\"score\"])) for s in students}\nprint(f\"Lookup : {score_lookup}\")\n\n# Dict comprehension with filter: honours students only\nhonours: dict[str, float] = {str(s[\"name\"]): float(str(s[\"score\"])) for s in students if float(str(s[\"score\"])) >= 80}\nprint(f\"Honours: {honours}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLookup : {'Alice': 92.0, 'Bob': 74.5, 'Carol': 88.0, 'Dan': 61.0}\nHonours: {'Alice': 92.0, 'Carol': 88.0}\n```\n:::\n:::\n\n\nSet comprehensions deduplicate automatically. Generator expressions compute values\n**lazily**: they use O(1) memory regardless of input size, making them ideal\ninside `sum()`, `any()`, and `all()`:\n\n::: {#138 .cell execution_count=67}\n``` {.python .cell-code}\nstudents: list[dict[str, object]] = [\n    {\"name\": \"Alice\", \"score\": 92.0, \"major\": \"CS\"},\n    {\"name\": \"Bob\", \"score\": 74.5, \"major\": \"Math\"},\n    {\"name\": \"Carol\", \"score\": 88.0, \"major\": \"CS\"},\n    {\"name\": \"Dan\", \"score\": 61.0, \"major\": \"Physics\"},\n]\n\n# Set comprehension: unique majors\nmajors: set[str] = {str(s[\"major\"]) for s in students}\nprint(f\"Majors : {sorted(majors)}\")\n\n# Generator expression: lazy evaluation; ideal inside sum/any/all\ntotal: float = sum(float(str(s[\"score\"])) for s in students)\nany_fail: bool = any(float(str(s[\"score\"])) < 70 for s in students)\nall_pass: bool = all(float(str(s[\"score\"])) >= 60 for s in students)\n\nprint(f\"Mean          : {total / len(students):.1f}\")\nprint(f\"Any fail (<70): {any_fail}\")\nprint(f\"All pass (>=60): {all_pass}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMajors : ['CS', 'Math', 'Physics']\nMean          : 78.9\nAny fail (<70): True\nAll pass (>=60): True\n```\n:::\n:::\n\n\n<div style='background:#FFF1E6;border-left:5px solid #EA580C;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#9A3412;font-weight:bold'><i class=\"bi bi-puzzle-fill\"></i> Activity 7 - Cohort Score Report</span><br><br>\n<b>Goal:</b> Using a single comprehension for each, produce the outputs below from <code>records</code>.\n<pre style='background:#FCE8DA;padding:10px;border-radius:4px;font-size:0.9em'>records = [\n    {'name': 'Alice', 'scores': [88, 92, 85]},\n    {'name': 'Bob',   'scores': [62, 70, 58]},\n    {'name': 'Carol', 'scores': [91, 95, 89]},\n]\n\n# 1. List of averages (one float per student)\naverages = [82.33, 63.33, 91.67]\n\n# 2. Dict mapping name -> average (rounded to 2 dp)\navg_map = {'Alice': 88.33, 'Bob': 63.33, 'Carol': 91.67}\n\n# 3. Set of unique student names who scored >= 80 average\ntop = {'Alice', 'Carol'}</pre>\n</div>\n\n::: {#140 .cell execution_count=68}\n``` {.python .cell-code}\nrecords: list[dict[str, object]] = [\n    {\"name\": \"Alice\", \"scores\": [88, 92, 85]},\n    {\"name\": \"Bob\", \"scores\": [62, 70, 58]},\n    {\"name\": \"Carol\", \"scores\": [91, 95, 89]},\n]\n\n# TODO: 1. list of averages\naverages: list[float] = ...\n\n# TODO: 2. name -> average dict\navg_map: dict[str, float] = ...\n\n# TODO: 3. set of names with average >= 80\ntop: set[str] = ...\n\nprint(f\"averages: {averages}\")\nprint(f\"avg_map : {avg_map}\")\nprint(f\"top     : {top}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\naverages: Ellipsis\navg_map : Ellipsis\ntop     : Ellipsis\n```\n:::\n:::\n\n\n## Capstone: Monte Carlo Pi Estimation\n\nThis activity ties together everything from Part 1: variables, lists, for loops,\nrandom numbers, functions, and comprehensions, to estimate the value of π\nusing a simulation technique called **Monte Carlo integration**.\n\n### The idea\n\nImagine a unit circle (radius = 1) inscribed in a 2×2 square.\nA random point `(x, y)` with `x, y ∈ [−1, 1]` falls inside the circle if\n`x² + y² ≤ 1`.\n\nThe ratio of the circle's area to the square's area is π/4.\nIf we throw millions of random points and count how many land inside the circle,\nthe proportion converges to π/4, so `π ≈ 4 × (hits / total)`.\n\n```\n  ┌──────────────┐\n  │    ·  ●  ·   │   ● inside circle  → hit\n  │  ●       ●   │   · outside        → miss\n  │    circle    │\n  │  ●       ●   │\n  │    ·  ●  ·   │\n  └──────────────┘\n   π/4 ≈ hits/total\n```\n\nThis is a real technique used in finance, physics, and ML for problems\nthat are too complex to solve analytically.\n\n**Step 1:** Write a helper that checks whether a point is inside the unit circle:\n\n::: {#143 .cell execution_count=69}\n``` {.python .cell-code}\nimport math\n\n\ndef in_unit_circle(x: float, y: float) -> bool:\n    \"\"\"Return True if (x, y) lies inside the unit circle (radius = 1).\"\"\"\n    return x**2 + y**2 <= 1.0\n```\n:::\n\n\n**Step 2:** Simulate random points and count how many land inside the circle. `random.seed()` makes results reproducible. Always set a seed before any simulation:\n\n::: {#145 .cell execution_count=70}\n``` {.python .cell-code}\nimport random\n\nrandom.seed(42)  # fix seed for reproducibility\n\nN_POINTS: int = 1_000_000\ninside: int = sum(\n    1\n    for _ in range(N_POINTS)\n    if in_unit_circle(random.uniform(-1, 1), random.uniform(-1, 1))  # noqa: S311\n)\n\npi_estimate: float = 4 * inside / N_POINTS\nprint(f\"Points       : {N_POINTS:,}\")\nprint(f\"Hits (inside): {inside:,}\")\nprint(f\"pi estimate  : {pi_estimate:.5f}\")\nprint(f\"math.pi      : {math.pi:.5f}\")\nprint(f\"Error        : {abs(pi_estimate - math.pi):.5f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPoints       : 1,000,000\nHits (inside): 785,061\npi estimate  : 3.14024\nmath.pi      : 3.14159\nError        : 0.00135\n```\n:::\n:::\n\n\n**Step 3:** See how the estimate improves as `N` grows: the law of large numbers at work:\n\n::: {#147 .cell execution_count=71}\n``` {.python .cell-code}\nimport math\nimport random\n\nrandom.seed(0)\n\nfor n in [100, 1_000, 10_000, 100_000, 1_000_000]:\n    hits = sum(\n        1\n        for _ in range(n)\n        if in_unit_circle(random.uniform(-1, 1), random.uniform(-1, 1))  # noqa: S311\n    )\n    est = 4 * hits / n\n    error = abs(est - math.pi)\n    print(f\"  n={n:>9,}  pi={est:.5f}  error={error:.5f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  n=      100  pi=3.28000  error=0.13841\n  n=    1,000  pi=3.02000  error=0.12159\n  n=   10,000  pi=3.14480  error=0.00321\n  n=  100,000  pi=3.13056  error=0.01103\n  n=1,000,000  pi=3.14178  error=0.00019\n```\n:::\n:::\n\n\n<div style='background:#EAF3FA;border-left:5px solid #0369A1;padding:14px 18px;border-radius:6px;margin:16px 0'>\n<span style='color:#0369A1;font-weight:bold'><i class=\"bi bi-info-circle-fill\"></i> What you just used</span><br><br>\n<ul>\n<li><b>Variables & types</b>: <code>N_POINTS: int</code>, <code>pi_estimate: float</code></li>\n<li><b>Functions</b>: <code>in_unit_circle()</code> with type hints</li>\n<li><b>for loop</b>: iterating N times, building results</li>\n<li><b>Comprehension</b>: <code>sum(1 for _ in range(n) if ...)</code></li>\n<li><b>random module</b>: <code>seed()</code> for reproducibility, <code>uniform()</code> for sampling</li>\n<li><b>math module</b>: <code>math.pi</code> as ground truth</li>\n</ul>\nThis exact pattern (sample randomly, count outcomes, estimate a ratio) appears in A/B testing, Bayesian inference, and reinforcement learning.\n</div>\n\n## Summary\n\n| Concept | Key rule |\n|---|---|\n| Type hints | `x: int`, `list[float]`, `dict[str, int]`, `X \\| None`, checked by `ty` but not enforced at runtime |\n| f-strings | `f'{var=}'` for debugging; `f'{val:.2f}'` for formatting |\n| Strings | `.strip()`, `.split()`, `.join()`, `.replace()` cover most data cleaning |\n| `list` | Ordered, mutable; use `.copy()` not `=` when you need independence |\n| `tuple` / `NamedTuple` | Immutable records; unpack with `a, b = t` or `a, *rest, b = t` |\n| `dict` / `TypedDict` | Key-value; merge with `\\|`; typed schema with `TypedDict` |\n| `set` | Unique values, O(1) membership; `\\|` union, `&` intersection, `-` difference |\n| `Counter` | Frequency counts; `.most_common(n)` |\n| `defaultdict` | Group items without `KeyError`; `defaultdict(list)` |\n| `deque` | Sliding windows; `maxlen=` auto-drops oldest |\n| `match/case` | Structural pattern matching on values, dicts, lists (3.10+) |\n| `enumerate` / `zip` | Always prefer these over manual index counters |\n| `while` / `break` / `continue` | For indefinite loops, early exit, and skipping bad data |\n| Walrus `:=` | Assign inside a condition to avoid re-computing |\n| Comprehensions | `[expr for x in it if cond]`; use generators `(...)` inside `sum()` / `any()` / `all()` |\n\n\n**Next:** `02-python-patterns.ipynb`, covering functions, lambdas, `*args`/`**kwargs`, dataclasses, modules, exception handling, and file I/O with `pathlib`.\n\n",
    "supporting": [
      "01-python-core_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}
